### ISSUE TITLE
Failure to build on 32bit/Windows

### ISSUE THREAD

**Issue by EionRobb** [hoehermann/purple-gowhatsapp#1]
```
C:/Go/bin/go build -buildmode=c-archive -o purplegwa.a purplegwa.go
# command-line-arguments
.\purplegwa.go:140:5: cannot use _Ctype_uint(len(message.data)) (type _Ctype_uint) as type _Ctype_ulonglong in field value
make: *** [Makefile.mingw:49: purplegwa.a] Error 2
```

I don't know anything about go, but to get it to compile I replaced it with
```
blobsize  : C.ulonglong(len(message.data)),
```
and that seems to work

**Comment by EionRobb** [comment]
I've managed to get it building using https://github.com/EionRobb/purple-gowhatsapp/commit/692d8b90c3af2b62ad1bea6e4e4f53ead519a7ac and built a (13 megabyte!) dll at https://eion.robbmob.com/libgowhatsapp.dll

**Comment by hoehermann** [comment]
I don't know anything about go either. :)

[The spec](https://golang.org/ref/spec#Numeric_types) says [len](https://golang.org/pkg/builtin/#len) returns an `int` and "uint is either 32 or 64 bits and int is the same size as uint". `size_t` looked like a sensible choice for a C equivalent, but apparently I was mistaken. I am glad you tackled that issue and grateful for your Windows build. 👍 I was told, go links everything it ever needs statically into its binaries so they tend to be quite sizeable.

**Comment by EionRobb** [comment]
I think the compiler complaint is that the `struct gowhatsapp_message` in purplegwa.h:42 is defined as a 64bit int, but size_t is only 64bit on 64bit platforms, so it needed the `C.ulonglong()` cast in order to make a valid size for the `struct gowhatsapp_message`

**Comment by hoehermann** [comment]
Very right.

**Comment by hoehermann** [comment]
Should be okay with f00c286.
