### ISSUE TITLE
purple-whatsmeow filename

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#100]
Can it be build to another filename than libgowhatsapp ? E.g. to libgowhatmeow.dll?

**Comment by hoehermann** [comment]
To avoid collisions, you can rename it to anything you like. The file name has no meaning to Pidgin. :)

I am not sure whether to promote the new version as "libwhatsmeow.dll" (new thing) or  "libgowhatsapp.dll" (replacement).

**Comment by hoehermann** [comment]
I made a decision: The new variant is consistently called libwhatsmeow.dll|so. :)
