### ISSUE TITLE
Aliased account displays message "(11:52:37) xxxx@s.whatsapp.net is now known as Werka."

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#101]
Within chat, from time to time, I got message `(11:52:37) xxxx@s.whatsapp.net is now known as Werka.`.
After scanning QR code, this contact got 'Werka' name, and I aliased it to name with surname.
Can this "is now known" message be supressed?

**Comment by hoehermann** [comment]
Thank you for the report. I put it on the list of things to fix.

**Comment by pkar70** [comment]
Thanks :)

**Comment by hoehermann** [comment]
While it popped up once more, I have not seen this happening in quite some time. Assumed to be fixed by 454ba1a.
