### ISSUE TITLE
Display last seen attribute of arbitrary numbers

### ISSUE THREAD

**Issue by enskpl** [hoehermann/purple-gowhatsapp#108]
Hello,
I don't know Go or C at all, I've never worked in either of them before.
But I want to use this package.
Even though I struggled for hours, I could not understand how to install and run it, I am constantly encountering errors.
Could someone please send me a detailed document on how to install and run this project?
Thanks.

**Comment by hoehermann** [comment]
Which operating system are you using?

**Comment by enskpl** [comment]
@hoehermann Windows 10 64bit

**Comment by hoehermann** [comment]
Just use the latest binary provided [here](https://buildbot.hehoe.de/purple-whatsmeow/builds/libwhatsmeow.dll). Place it into the "plugins" directory of your Pidgin installation (or the configuration directory).

**Comment by enskpl** [comment]
@hoehermann 
Thanks, I'll try.
I have one more question, does this package allow to see the presence activities of people non-contacts?

**Comment by hoehermann** [comment]
This plug-in shows the "online", "offline" and "last seen" information about the contacts on Pidgin's buddy list as provided by the WhatsApp servers. I do not know if WhatsApp servers provide information about people who have not added _you_ to _their_ contacts. 

You can add arbitrary numbers to your local buddy list. The list is never uploaded, only downloaded upon request. For this reason, your local buddy list may differ from the contacts stored on your phone or displayed in WhatsApp Web.

**Comment by enskpl** [comment]
@hoehermann 
I tried, but I can't get the last seen information of the number that has non-contact.
Do you have any idea how to overcome this?
This is a new update released by WhatsApp about 3 weeks ago, but after the update there are apps that can do this.

**Comment by hoehermann** [comment]
If I try to subscribe for presence updates of people I who do not know me, WhatsApp servers deny the access: `<presence from="REDACTED@s.whatsapp.net" last="deny" type="unavailable"/>` I am quite confident this is a privacy feature and I do not want to work around it. And you should be respecting people's wishes for privacy, too.

If there are other apps which somehow manage to pull confidential information from WhatsApp servers, feel free to use them. I do not want to have any part in shady operations.

**Comment by enskpl** [comment]
@hoehermann 
Did you get this information when the person was online?
`<presence from="REDACTED@s.whatsapp.net" last="deny" type="unavailable"/>`

**Comment by hoehermann** [comment]
Based on my observations, I receive

* `type="available"` when the contact is online
* `last="1234567890" type="unavailable"` when the contact is currently offline and allows viewing the time they were last seen
* `last="deny" type="unavailable"` when the contact is currently offline and does not allow viewing the time they were last seen
* `last="deny"` when the contact does not want to make their presence public
* nothing at all when the contact does not know my number

Note: When a contact switches from "available" to "unavailable", pidgin will keep track of the time they went offline even if `last="deny"`. As far as I know, in order to observe the change, you have to be online and the contact must have you on their contact list.

**Comment by enskpl** [comment]
@hoehermann 
Thanks for the answer.
But can we get the person's offline time without we being in their contact list?

**Comment by hoehermann** [comment]
As far as I can tell: No. WhatsApp servers do not transmit that information via whatsmeow.

**Comment by enskpl** [comment]
@hoehermann So is it possible to get it in another library? Do you know about this?

**Comment by hoehermann** [comment]
No, I do not know about this and I do not want to do any research in that direction. _You_ claimed "there are apps that can do this" two days ago.

**Comment by enskpl** [comment]
@hoehermann Yes, I've seen mobile apps that do this. I'm looking for a library that does the same thing.

**Comment by hoehermann** [comment]
It is out of this plug-in's scope. Also, this plug-in only uses the library whatsmeow and is in no other way affiliated with it.
