### ISSUE TITLE
Doesn not compile since commit 4fa79ff7c34a96c5b5e9111c9fcdced3f7a13bce

### ISSUE THREAD

**Issue by pzajda** [hoehermann/purple-gowhatsapp#11]
When I type make, I have the following error:
> ./purplegwa.go:79:13: assignment mismatch: 2 variables but 1 values

I use Debian Stretch 64-bits.

**Comment by hoehermann** [comment]
For 4fa79ff, you need [go-whatsapp 4be474a](https://github.com/Rhymen/go-whatsapp/commit/4be474aa8320557ead966e74d357ca975117e360).  
For earlier commits, you need [go-whatsapp e51cd7d](https://github.com/Rhymen/go-whatsapp/commit/e51cd7d0bbd46ddee94a6b2115d4c8d9c2e86a33).

`go get -u github.com/Rhymen/go-whatsapp` will probably solve this issue in your case.

On a side note: I need to figure out how to pin the go module version.

**Comment by pzajda** [comment]
Thanks for your answer, the solution you given works perfectly.
