### ISSUE TITLE
my contacts appear offline

### ISSUE THREAD

**Issue by jeremyp3** [hoehermann/purple-gowhatsapp#111]
since this latest version, I notice that my contacts appear disconnected even though I have checked the box: "checked Display offline contacts as away"

I reset my account in pidgin with the same result after the second connection.

**Comment by hoehermann** [comment]
Is your own state set to "away" or "available" (online)?

**Comment by jeremyp3** [comment]
my pidgin status is away. effectively. maybe there could be an option, so you can choose :)

**Comment by hoehermann** [comment]
I want to fix the conditions so contacts are requested when setting any status, not only "available".

**Comment by jeremyp3** [comment]
It's a good idea. I will be happy to test it

**Comment by hoehermann** [comment]
Closing due to lack of answer. In case the problem persists, feel free to respond.
