### ISSUE TITLE
I can't build the library

### ISSUE THREAD

**Issue by enskpl** [hoehermann/purple-gowhatsapp#112]
```
ubuntu@instance-1:~/Desktop/purple-gowhatsapp-whatsmeow/build$ cmake --build .
[ 14%] Built target purple-dummy
[ 19%] Updating go modules...
No such file or directory
make[2]: *** [src/go/CMakeFiles/purple-go-whatsapp.dir/build.make:82: ../src/go/go.mod] Error 1
make[2]: *** Deleting file '../src/go/go.mod'
make[1]: *** [CMakeFiles/Makefile2:116: src/go/CMakeFiles/purple-go-whatsapp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

Any idea for this?

**Comment by hoehermann** [comment]
Is the go executable in your PATH? If you do not want to modify your PATH environment variable, you can specify the go executable in the cmake variable `CMAKE_Go_COMPILER`.

**Comment by hoehermann** [comment]
Closing due to lack of answer. If the problem persists, feel free to respond.

**Comment by terminaldweller** [comment]
i had the same issue building on debian bullseye with go 1.19 from backports. the go binary was not in path. adding it fixed the issue.
cheers.
