### ISSUE TITLE
QR code required on every connection (session not stored)

### ISSUE THREAD

**Issue by blacklight** [hoehermann/purple-gowhatsapp#115]
I bumped into [this issue](https://github.com/hoehermann/purple-gowhatsapp/issues/96) earlier already, and back then it got fixed by a PR and a setting (`restore-session = true`). However, after migrating to _whatsmeow_ the issue is back (QR code is required on every connection), and the `restore-session` setting is also gone. Is it something you guys are aware of or am I missing something in the setup?

**Comment by hoehermann** [comment]
Oh, yes. For enabling bitlbee-compatible storage mechanisms, the setting `bridge-compatibility` must be enabled. Please let me know if that helps. In case `bridge-compatibility` has unwanted effects, please also let me know. [vitalyster](https://github.com/vitalyster) mentioned some issues with spectrum but did not elaborate.

PS: I should probably write a migration manual and mention it there.

**Comment by rvdborgt** [comment]
> PS: I should probably write a migration manual and mention it there.

That would be greatly appreciated :)
I was just wondering what I have to do to migrate.

**Comment by blacklight** [comment]
> For enabling bitlbee-compatible storage mechanisms, the setting bridge-compatibility must be enabled

Thanks, that did the trick! Is there a reason why this flag isn't enabled by default?

**Comment by hoehermann** [comment]
Yes. Firing a bitlbee-specific signal crashes Pidgin's debug view, see https://github.com/hoehermann/purple-gowhatsapp/issues/105#issuecomment-1032038677. I read through Pidgin's code and have not seen a way to overcome this programmatically.

**Comment by EionRobb** [comment]
You could look at what UI is running libpurple and set the flag automatically?
```
if (g_strcmp0(purple_core_get_ui(), "BitlBee") == 0) {
    purple_account_set_bool(account, "bridge-compatibility", TRUE);
}
```

**Comment by hoehermann** [comment]
That is a good idea. I was so focused on accessing `instance_table` (signals.c) directly that I forgot I could also check for BitlBee. 

Just now I noticed I can also try `purple_signal_get_values` to check whether the signal itself has been registered. It is just a shot in the dark and I did not test it at all. Feel free to give 6009ffa from the https://github.com/hoehermann/purple-gowhatsapp/tree/dev branch a try.

Thank you for your help, both of you. :heart:

**Comment by hoehermann** [comment]
@BlackLight Did you have the chance to test the dev branch against Bitlbee?

**Comment by blacklight** [comment]
> Did you have the chance to test the dev branch against Bitlbee?

In my case the `bridge-compatibility` option already did the trick.

**Comment by hoehermann** [comment]
Okay. In that case, I just hope my recent changes did not break anything. For now, I guess this is fixed. :)
