### ISSUE TITLE
get into Debian

### ISSUE THREAD

**Issue by calestyo** [hoehermann/purple-gowhatsapp#116]
Hey.

Would be awesome if you could get this into Debian (from which many other distros would sooner or later inherit it).

Cheers,
Chris.

**Comment by hoehermann** [comment]
Hi Chris

Thank you for the interest in this plug-in. Unfortunately, I do not feel up to the task. Being the maintainer requires a higher level of diligence and dedication than I am willing to put into this project. Keep in mind that I do this for fun and in my spare time.

Kind Regards
Hermann
