### ISSUE TITLE
duplicating members in chat

### ISSUE THREAD

**Issue by lazyest** [hoehermann/purple-gowhatsapp#117]
Seems like after reconnect or something I have all members of chat added once again. Just now I see everybody for 3 times and its only middle of day :) Restarting pidgin resolves issue for a while.

**Comment by lazyest** [comment]
Yes, I've disconnected whatsapp protocol and connect again, everyone added once again.

**Comment by hoehermann** [comment]
I am almost perfectly certain that I have seen a "user is in chat" function I did not use. Now I know why it exists. I expect this to be an easy fix.
