### ISSUE TITLE
Failed to pair device

### ISSUE THREAD

**Issue by RunningX** [hoehermann/purple-gowhatsapp#118]
Hey,
i got that message after scanning the QR-Code:

"[Client] Failed to pair device: failed to save device store: no such table: whatsmeow_device"

Try rebuild and delete the whatsmeow.db and create new account, same again

RnX

**Comment by hoehermann** [comment]
Are you using the default database parameters or something special?

**Comment by RunningX** [comment]
I just installed pidgin and the plugin. Nothing spezial 

I use Manjaro KDE its based on Arch linux installed  pidgin via Pacman and the plugin via AUR

**Comment by hoehermann** [comment]
Confirmed. The database is not populated at all. I am not sure whether a recent change introduced a bug in whatsmeow or if I am now using it wrong. Until I find out, you can extract the empty whatsmeow.db from [this archive](https://github.com/hoehermann/purple-gowhatsapp/files/8446363/empty_database.zip) to start.

**Update:** Found the bug. It was actually sitting there for an entire month, not affecting existing users. Looks like you are the first new user in the last thirty days. I somehow thought this plug-in was more popular. :(

**Comment by RunningX** [comment]
THX it works, great

**Comment by JackDandy** [comment]
> Looks like you are the first new user in the last thirty days. I somehow thought this plug-in was more popular. :(

You are mistaken, people do not know to switch to the new meow build, is all. I only found it due to crashing old build, so do NOT think that you work is not popular - it is of great use! and people will come, just slowly.
