### ISSUE TITLE
[feature] search or download contacts from phone

### ISSUE THREAD

**Issue by benny59** [hoehermann/purple-gowhatsapp#12]
I managed to compile, configure and run the plugin for my two SIMs
Messages can be sent, but a conversation can be started only if you know the phone number of the buddy in the form 3988888888@s.whatsapp.net.

Any chance to filter the buddy via contact name ?

regards
benny

**Comment by hoehermann** [comment]
I guess so. There are functions called `Search` and `Contacts` in [contact.go](https://github.com/Rhymen/go-whatsapp/blob/405d10a2f16c7893e392b7196ae803abf40b0523/contact.go), but they are not documented. As a result, I do not exactly know how they are supposed to be used. It may or may not be possible to download the list of contacts from the phone to the buddy list. However, I am busy with other things and do not want to dive into this right now. 

Pull requests are welcome. :)

**Comment by hoehermann** [comment]
@benny59 This is now implemented. Thank you for your contribution, @nihilus. :)
