### ISSUE TITLE
whatsmeow : no automatic reconnection after a lost connection

### ISSUE THREAD

**Issue by jeremyp3** [hoehermann/purple-gowhatsapp#124]
Hello,
When there is a loss of connection, the module deactivates with this message: "33xxxxxxxxx@s.whatsapp.net disable
[Client/Socket] Error reading from websocket: read tcp 192.168.80.10:39466->157.240.21.52:443: read: connection reset by peer"
if the module is not reactivated, it does not reconnect itself.

possible not to deactivate the module in this case, but to attempt an automatic reconnection?

thanks !

Jeremyp3

**Comment by Nardol** [comment]
I also encounter this issue and have to reconnect each time.
Having an automatic reconnection would be very useful.

**Comment by hoehermann** [comment]
This should be implemented in 44a9e16. Please re-open this issue if it does not cover all cases.
