### ISSUE TITLE
Installation instructions help

### ISSUE THREAD

**Issue by Industry** [hoehermann/purple-gowhatsapp#127]
Not an issue at all but a question on installation and usage.

I dropped the nightly build DLL into `\PortableApps\PidginPortable\Data\settings\.purple\plugins\libwhatsmeow.dll` but it's not showing up under the available accounts. Where do the other dependencies go?

Thank you!

**Comment by hoehermann** [comment]
These static builds are self-contained, there are no further dependencies (that is also why the files are so huge). The pixmaps with the protocol logo are optional. 

I have not tested the Windows builds in a while, there might be something wrong with them. At the moment, I do not have access to a Windows machine. Can I get back to you in a fortnight? 

Alternatively you may try to start Pidgin in debug mode: Right-Click next to the pidgin.exe while holding down shift, select "open PowerShell here", paste into the console window: `pidgin.exe -d > pidgin.txt` Wait for Pidgin to start, then close it. Examine the newly created text-file for any mentions of whatsmeow and post them here.

**Comment by Industry** [comment]
It might have been a configuration issue on my end. When I followed the instructions to do the debug, Pidgin ran with the plugin loaded and everything working fine.  
Appreciate the quick response!
