### ISSUE TITLE
Incompatibility with Conversation Colors plug-in

### ISSUE THREAD

**Issue by ZaxonXP** [hoehermann/purple-gowhatsapp#13]
Just did build form master.zip and added my existing WhatsApp account. I got this message "Scan this QR code within 20 seconds to log in." but no picture was displayed. What could be wrong? Do I need some Pidgin plugin enabled/installed?

Regards,
Piotr

**Comment by EionRobb** [comment]
Make sure you're not using the "Conversation Colors" plugin in Tools->Plugins as it will eat images and prevent them from displaying

**Comment by ZaxonXP** [comment]
Yes, that was the guilty one. Maybe it is worth adding this info to the README. :)

But what to do with this QR code? Should I scan it with some specific app? And then what?

**Comment by EionRobb** [comment]
Scan it with the WhatsApp app on your phone. This plugin talks with it as if you were using the web link to WhatsApp

**Comment by ZaxonXP** [comment]
I scanned it with the WebApp mode and then my Pidgin crashed.
[pidgin_log.txt](https://github.com/hoehermann/purple-gowhatsapp/files/3202187/pidgin_log.txt)

**Comment by hoehermann** [comment]
> Maybe [incopatibility with "Conversation Colors"] is worth adding this info to the README.

Good idea.

> I scanned it with the WebApp mode and then my Pidgin crashed.

An interesting one. It looks like a problem in the go-parts and I am not actually familiar with them. I cannot reproduce it on my machine. I am using go 1.10.4 and go-Rhymen/whatsapp@5d51009 on an amd64 Ubuntu "bionic". Which versions are you using?

**Comment by ZaxonXP** [comment]
`go version go1.11.5 linux/386`
The other I took using a command `go get github.com/Rhymen/go-whatsapp` (done yesterday) and I do not know how to check which version it is.
My system is: `Debian GNU/Linux 9.9 (stretch)`

I can do some tests for you, but you need to guide me what to do, as I am not so familiar with this `go` environment.

Regards,
Piotr

**Comment by hoehermann** [comment]
Thank you for your offer to help.

I suspect the problem either within go-whatsapp or an with the 32bit build (I have not tested them).

Can you `go run` the example `https://github.com/Rhymen/go-whatsapp/blob/master/examples/login`? `go get` has probably put it into `~/go/src/github.com/Rhymen/go-whatsapp/examples/login`. Does the same error occur?

**Comment by ZaxonXP** [comment]
```
user@localhost:~$ go run https://github.com/Rhymen/go-whatsapp/blob/master/examples/login
package https:/github.com/Rhymen/go-whatsapp/blob/master/examples/login: cannot find package "https:/github.com/Rhymen/go-whatsapp/blob/master/examples/login" in any of:
        /usr/lib/go-1.11/src/https:/github.com/Rhymen/go-whatsapp/blob/master/examples/login (from $GOROOT)
        /home/user/go/src/https:/github.com/Rhymen/go-whatsapp/blob/master/examples/login (from $GOPATH)
```
If I do the following:
```
user@localhost:~/go/src/github.com/Rhymen/go-whatsapp/examples/login$ go run main.go 
main.go:5:2: cannot find package "github.com/Baozisoftware/qrcode-terminal-go" in any of:
        /usr/lib/go-1.11/src/github.com/Baozisoftware/qrcode-terminal-go (from $GOROOT)
        /home/user/go/src/github.com/Baozisoftware/qrcode-terminal-go (from $GOPATH)
```
Is this what I supposed to do?

**Comment by hoehermann** [comment]
With the second approach, you are on the right track. I was under the impression, go downloads dependencies automatically. Somehow, it does not do so for you. Run `go get github.com/Baozisoftware/qrcode-terminal-go` and try again (repeat for all the missing packages).

**Comment by ZaxonXP** [comment]
After I did this `go get github.com/Baozisoftware/qrcode-terminal-go` now if I go to the `.../examples/login` and run `go run main.go` then I get the QR code in terminal. After I scan it with the WhatsApp mobile app I got the following:

```
login successful, session: <some long strings here>
```

**Comment by hoehermann** [comment]
Thank you for your help. This confirms your build of go-whatsapp is fine. It must be the way I am using it. I want to try and reproduce this error with a 32bit build. However, I am quite busy these days, do not expect anything before July.

**Comment by ZaxonXP** [comment]
Nothing urgent for me. I just found a bug I wanted to report and I am glad I could help. :)

**Comment by hoehermann** [comment]
I gave it a shot today and installed Debian 9 386 in a VM. Works flawlessly on the Debian-supplied libpurple-dev, go1.7.4 and go1.11.10 (a version close to the one used by you). I am sorry, I cannot reproduce the crash.

I leave this issue open due to the incompatibility with the Conversation Colors plug-in.

**Comment by leolca** [comment]
I'm also experiencing the same behavior... I've tried all available amd64 builds... pidgin crashes after the QR code window closes... either if I give okay or dismiss, it makes pidgin crashes.

**Comment by hoehermann** [comment]
This seems to have been fixed. Feel free to re-open the issue if it still happens with the whatsmeow rewrite.
