### ISSUE TITLE
crashes on group message recieve

### ISSUE THREAD

**Issue by samtrek** [hoehermann/purple-gowhatsapp#134]
The latest update causes pidgin to crash on receiving group messages. Currently on Linux with pidign 2.14.10, will you please take a look at it or have suggestions towards fixing it.

**Comment by hoehermann** [comment]
Confirmed. Thank you for the report. It does not actually crash on receiving a message, but shortly after. That is why I did not notice it during my trial runs. I have an idea what is wrong. Unfortunately, I cannot test it thoroughly right now.

**Comment by samtrek** [comment]
Yes you are right, I am in a Whatsapp group that most of its member are not in my contact list, did not know that was the reason for the crash, and also like you said the crash was not immediate, pidgin freezes for some few seconds before it eventually crashes.

I have moved to a lower version.

**Comment by hoehermann** [comment]
It looks like I was not on the right track. I will need some time to figure this one out.

**Comment by hoehermann** [comment]
[v1.7.0](https://github.com/hoehermann/purple-gowhatsapp/releases/tag/v1.7.0) should be fine.
