### ISSUE TITLE
Unknown presence online (this is a bug).

### ISSUE THREAD

**Issue by DumbGameMaker** [hoehermann/purple-gowhatsapp#135]
When trying to add my account i get this error. 

using fedora 36 and iOS

**Comment by hoehermann** [comment]
Thank you for the report. Indeed, "online" is not a presence string supported by WhatsApp. WhatsApp knows "available", "unavailable", and implicitly "offline" (see [gowhatsapp.h](https://github.com/hoehermann/purple-gowhatsapp/blob/2a86488/src/c/gowhatsapp.h#L7)). What front-end are you using?

**Comment by DumbGameMaker** [comment]
You mean like what IM app? Im just using Pidgin

**Comment by hoehermann** [comment]
That is really weird. In no place the plug-in lists "online" as a valid state. I have no idea why Pidgin would try to use "online" instead of "available".

**Comment by DumbGameMaker** [comment]
Ok if i add 'online' to the list of activities in whatsapp, it works

**Comment by hoehermann** [comment]
I am glad you could make it work.
