### ISSUE TITLE
[Question] Where this list buddy come from?, any option to hide non saved number?

### ISSUE THREAD

**Issue by reidsneo** [hoehermann/purple-gowhatsapp#137]
The plugin works great on kubuntu 22.04.1
sometime is crashed but still OK, I have question where this buddy list come from?
I don't remember have this many contact person on whatapps contact list neither phone addressbook, is it possible to hide and only show the saved contact list?
![image](https://user-images.githubusercontent.com/12298979/201805287-9d372239-85b5-4022-b65d-8e5300d76c00.png)
Thanks!

**Comment by hoehermann** [comment]
By default, the plug-in pulls all contacts from the WhatsApp servers. It is quite possible that is all contacts the account has ever interacted (with including other people only _seen_ in group chats). You can change this behaviour by disabling the option to fetch contacts, then delete all unwanted contacts from the buddy list.

**Comment by reidsneo** [comment]
Hi Thank you, I got it what I wanted "You can change this behaviour by disabling the option to fetch contacts"
this option is perfect, if this checked the pidgin keep crashing, so just sync on the first usage, then later uncheck it
the contact seem coming from group participant I belong to.
I will close the question / issue then, thanks!
