### ISSUE TITLE
Build fails after breaking changes on GetProfilePictureInfo on whatsmeow

### ISSUE THREAD

**Issue by blacklight** [hoehermann/purple-gowhatsapp#139]
A [recent change](https://github.com/tulir/whatsmeow/commit/29e2b3546dbc4f59d21a98572b97feb73947bf5d) on whatsmeow is breaking the build of this module.

The signature of `GetProfilePictureInfo` has changed:

```
./profile.go:53:64: too many arguments in call to handler.client.GetProfilePictureInfo
        have (types.JID, bool, string)
        want (types.JID, *whatsmeow.GetProfilePictureParams)
```

A PR is on its way.

**Comment by hoehermann** [comment]
Thank you for the report and the improvements. I want to merge them next week.
