### ISSUE TITLE
[FEATURE REQUEST] website card?

### ISSUE THREAD

**Issue by curchunflo13** [hoehermann/purple-gowhatsapp#14]
Hello! Thank you for your work! It works for me. 

When I send a link vía WhatsappWeb or the Android app it has a websitecard previsualization, but when I post it from pidgin it does not make the preview. Have you thought to create this feature in the future??

Thank you very much

**Comment by hoehermann** [comment]
Hi

Thank you for your request. In fact, I have not thought of adding a feature for sending a website card. The official WhatsApp client (and Pidgin) already detect website links automatically and make them navigatable. So, no, I probably won't implement this feature myself. If anyone else wants to do so: Pull requests are always welcome. :)

Kind Regards
