### ISSUE TITLE
Can send messages only after restart

### ISSUE THREAD

**Issue by 00sapo** [hoehermann/purple-gowhatsapp#142]
Messages can be sent only after restarting for me. Is this intended? In this case, it should be added to the "installation" section in the Readme...

**Comment by hoehermann** [comment]
Thank you for the report. Does this happen once right after scanning the QR code? Or every time after starting Pidgin?

**Comment by 00sapo** [comment]
Only once after the qr code

**Comment by hoehermann** [comment]
It is not intended. I have noticed it happening, but I do not want to spend much time on fixing it. For most users scanning the QR code is a one-time thing. I want to add it to the read-me, though.

**Comment by hoehermann** [comment]
This is happening to other people, too: https://github.com/tulir/whatsmeow/issues/62

**Comment by hoehermann** [comment]
Although not a technical solution, this behaviour is documented in the README, which is "good enough" in my book.
