### ISSUE TITLE
nil pointer dereference gowhatsapp_go_query_group_participants

### ISSUE THREAD

**Issue by samtrek** [hoehermann/purple-gowhatsapp#145]
After updating to the latest purple-gowhatsapp, pidgin suddenly freezes and crashes, I ran pidgin from terminal and the following is the output of the crash

`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c8 pc=0x7ff93f8c46ee]

goroutine 17 [running, locked to thread]:
main.gowhatsapp_go_query_group_participants(0x55596da4f380, 0xc000006601?)
`

**Comment by hoehermann** [comment]
Thank you for the report. It looks like me being lazy finally catches up to me as seen in [these TODOs](https://github.com/hoehermann/purple-gowhatsapp/blob/d6f69a77e4d0c605212ad75d2f1d34b634d586fe/src/go/bridge.go#L151). I want to look into it tonight. Did you build from the default branch whatsmeow or tag v1.8.0?

**Comment by samtrek** [comment]
Default branch, it seems to be because it is automatically updated by my package manager (Archlinux, AUR).

**Comment by hoehermann** [comment]
Feel free to try again with a1fdc38. The issue probably won't be resolved, but we should get more debug information.

**Comment by samtrek** [comment]
I have updated to `a1fdc38` and it seems as if it is somehow stable for now, have not observed any crahses so far, so should the issue be closed?

**Comment by hoehermann** [comment]
Yes. In case the problem arises again, just re-open this issue. :)

Side-note: This can only happen if the plug-in tries to get information on a group without knowing the group ID. This should not be happening in the first place.
