### ISSUE TITLE
Cannot get group information due to timeout

### ISSUE THREAD

**Issue by samtrek** [hoehermann/purple-gowhatsapp#146]
After the resolving of the issue below

[issue 145](https://github.com/hoehermann/purple-gowhatsapp/issues/145)

The plugin disables itself at given intervals, and fails to re-enable itself once again
`Cannot get group information due to &errors.error String{s:"info query timed out"}`

**Comment by hoehermann** [comment]
Thank you for the report. That actually explains a lot of different issues regarding group information as reported by other users. I want to look into it tonight. 

I already can see some possibilities:  
A) Make this a transient error with an automated reconnect.  
B) Ignore the error (participant list will be empty until the user requests a refresh manually via `/participants`).  
C) Automatically retry synchronously until the request succeeds (locking up the GUI in the process).  
D) Automatically retry in the background. Participant list will remain empty, possibly forever, until WhatsApp servers decide to answer.  
What is your opinion?

**Comment by samtrek** [comment]
my opinion on the possibilities you listed above
1. If the auto-reconnect is not too often it can be acceptable, but if the plugin reconnects too often it may lock up pidgin making it unusable.
2. The number two solution is also ok, I for one dont check the members of a group, however `/participants` should be shown as part of a guide for those who want to know the members of a group.
3. This may lock up pidgin making it unusable for other plugins. And may lead to crashing of Pidgin if this persist for a long period of time.
4. If this does not lead to locking of accounts by whatsapp (due to too much query to whatsapp servers) and does not prevent the use of the pidgin app, it is a acceptable. Actually I will prefer this.
to be fair option `B` is the best, but I prefer option `D`

keep up the good work.

**Comment by hoehermann** [comment]
I went with option D. Let me know if ee6ce7c works better.

**Comment by samtrek** [comment]
Seems ee6ce7c has put an end to the issue raised, I will be closing this issue and will open anther issue if similar problems arise. Thank you once again for your effort, really enjoying the plugin.
