### ISSUE TITLE
Inline image display

### ISSUE THREAD

**Issue by samtrek** [hoehermann/purple-gowhatsapp#149]
I just noticed that the `inline images` display option is no longer working for me. Downloads the image correctly and can be assessed with a file browser, but the image is not inserted into conversations or chats.

As a fall back I think the images sent or received should a have link above or below it, this will also help the history plugin to keep a log of the images sent or received after the conversation window or chat window is closed. I could have disabled the `inline images` option but I dont want to use the image viewer for every image sent or received.

**Comment by samtrek** [comment]
Seems what I said above is somehow wrong, the images are not saved when `inline images` is enabled, I am using the `auto accept` plugins for some certain contacts (to automate things) and when I checked the default saving folders the images sent were not there, After disabling the option the `auto accept` plugin started working as it should do with image files.

**Comment by hoehermann** [comment]
The way it is currently implemented, the setting is mutually exclusive. So you have the image either embedded or stored in a file. I should be able to enhance the setting to offer all three options "inline only", "store only", and "both".

**Comment by brianjmurrell** [comment]
I'm confused.  I don't have the _Autoaccept_ plugin enabled and I do have _Inline images_ enabled in this plugin's _Advanced_ settings but when an image is sent to me all that I see in Pidgin is `<img id="1"/>`.

Is this the expected behaviour?  Is there no way to get images inline in Pidgin?

**Comment by heeplr** [comment]
> but when an image is sent to me all that I see in Pidgin is <img id="1"/>

Same here with spectrum2 + Conversations. Inline image display used to work, now just this tag is displayed (with increasing id value, when multiple images are received)

**Comment by hoehermann** [comment]
@brianjmurrell @heeplr Thank you for the report. Indeed, I broke that in 152d554. I want to fix it soon.

**Comment by hoehermann** [comment]
In https://github.com/hoehermann/purple-gowhatsapp/tree/dev, there is a new option `handle-images` with the choices `inline`, `xfer`, `both`. Does that improve the situation for you?

**Comment by brianjmurrell** [comment]
@hoehermann It sure does!  Getting images inline now.  Thanks!
