### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by czarekkwasny** [hoehermann/purple-gowhatsapp#15]
Hello,

I'm trying to compile the plugin under Fedora 30 but resulting library doesn't load into Pidgin. I tried the binary from https://ssl.hehoe.de/temp/libgowhatsapp_x86_64.so but it throws an error at login: 

error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

I also noticed the compiled file is smaller (5.8mb) compared to the downloaded binary (8.1mb), so it apparently doesn't compile correctly, but I don't get any errors either. (the specific commit cc103e6 pointed in readme file is unavailable).

**Comment by czarekkwasny** [comment]
OK, sorry for the noise turns out I was using wrong version of the compiler.

**Comment by hoehermann** [comment]
The binary I supplied indeed was outdated. It is up-to date now. Thanks for the report.

**Comment by curchunflo13** [comment]
Hello, I am having the same error, I have downloaded the plugin from https://ssl.hehoe.de/temp/libgowhatsapp_x86_64.so

could you please tell me where to find the updated .so?
