### ISSUE TITLE
no sound on message recieved (group only)

### ISSUE THREAD

**Issue by RustedAperture** [hoehermann/purple-gowhatsapp#151]
When receiving a message in a group chat there is no notification sound, however, when receiving a message from an individual person there is.

Perhaps I'm missing something in the settings.

**Comment by hoehermann** [comment]
Thank you for the message. You are not missing anything. For identifying chats, Purple uses numeric IDs. WhatsApp uses a string (at least historically). It makes chat lookup a bit tedious. Also I did not find out how to use `purple_conv_chat_get_nick(chat)`, yet. Hence I use a non-standard way of writing messages to chats which does not include firing the event which ultimately plays the sound.

Note to self: Organize chats based on numeric IDs and use `serv_got_chat_in`. Find out how to incorporate `purple_conv_chat_get_nick(chat)`.  
Or just manually do a `purple_signal_emit(purple_conversations_get_handle(), "received-chat-msg", g->account, who, message, conv, flags);`.

**Comment by EionRobb** [comment]
If it helps, in other prpls I've just done a `g_str_hash()` (from the GHashTable set of functions) to convert chat names into chat id's. Works pretty well.

**Comment by hoehermann** [comment]
This should be working now.
