### ISSUE TITLE
Cannot open group Chat

### ISSUE THREAD

**Issue by 82MHz** [hoehermann/purple-gowhatsapp#156]
I'm on endeavouros (Arch Linux) with Pidgin version 2.14.12 and purple-gowhatsapp-git from AUR version 1.9.0r206_-1.

I can download the contact list from whatsapp, open individual chats but cannot join or open group chats. When I right click on an existing group chat and click "join", simply nothing happens.

I also don't get any notifications on messages in a group chat.

Are there any logs where I can see what's failing?

**Comment by hoehermann** [comment]
Confirmed. Maybe I can look into this tonight.

**Comment by hoehermann** [comment]
A classic mistake. Thank you for pointing it out.

**Comment by 82MHz** [comment]
Ah, the number of times I've made that exact mistake ;)

Works perfectly now, thanks for the quick fix and the amazing plugin! :)
