### ISSUE TITLE
Unable to send message: sending message timed out

### ISSUE THREAD

**Issue by czarekkwasny** [hoehermann/purple-gowhatsapp#16]
I've been testing the plugin for 2 days and the issue that hits me is that for almost every message I send, I get the following error in the conversation window:

    (19:30:45) Unable to send message.
    (19:30:45) Unable to send message: sending message timed out

The message is actually received and I can see it on my Android device. I checked the log but it only says:

    (19:30:45) gowhatsapp: Recieved: at 0 id  remote 00123456789@s.whatsapp.net sender (fromMe 0)

I searched for the issue but only found this thread: https://github.com/Rhymen/go-whatsapp/issues/38 which suggests refactoring the code.

Is there a possible way to fix this issue? (I have no problems with receiving the messages from the Android device, including the ones marked as unsent in conversation window).

Pidgin 2.13.0-9.fc30 (libpurple 2.13.0)
f07927902113041d6fa291293d9205ea4f05e9e6

**Comment by hoehermann** [comment]
I am unable to reproduce this issue with neither go-whatsapp cc103e6 nor the current c872073. Sending messages is working fine over here (no false errors are reported). Is is quite possible you are facing a problem from within Rhymen's go-whatsapp. Does the [example](https://github.com/Rhymen/go-whatsapp/tree/master/examples/sendTextMessages) work for you?

**Comment by czarekkwasny** [comment]
Yes, upon further investigation, it looks like the problem is on a much deeper level.

I found the reason behind the timeout messages: they only appear when the Android device is in the sleep mode, as soon as I wake it up the messages go through without delay or any issues. It's probably the old version of Android (6.0.1) that prevents the Rhymen's integration from working correctly (although this doesn't happen via native Whatsapp web client, it's probably configured to handle long delays for older devices like mine).

The example provided works in the same way, returning timeout when the device is in sleep mode and working correctly as soon as it's on.

I managed to compile a custom binary that works for my specific case. Thank you for helping me to figure out the cause of the issue.

**Comment by hoehermann** [comment]
You are welcome.

**Comment by brianjmurrell** [comment]
Can we reopen this please?  I am also hitting this on my Oreo Android device.

**Comment by brianjmurrell** [comment]
I don't think this has anything to do with the app being in sleep mode.  I can get this randomly while i am successfully sending and receiving messages without touching my phone (i.e. screen is off, sitting on my desk idle).

The message even sends despite the error.

**Comment by hoehermann** [comment]
Then this is an issue with the underlying go-whatsapp, not within this plug-in. Please head over to https://github.com/Rhymen/go-whatsapp/issues/38.

**Comment by radasbona** [comment]
I have still this problem. 
Ubuntu Mate 18.04 - Android 7.0.1 - Plugin Version 0.0.7 
Receiving works fine
