### ISSUE TITLE
Add support for disappearing messages

### ISSUE THREAD

**Issue by s-h-r-i** [hoehermann/purple-gowhatsapp#162]
Looking at [WhatsMeow discussion thread](https://github.com/tulir/whatsmeow/discussions/259), this feature seems supported. Consider adding it to libpurple? 

Thanks for the great work so far!

**Comment by hoehermann** [comment]
Thank you for the suggestion. It looks like can add *sending* disappearing messages. Also mentions. And quotes. I use quotes quite often.

I would make disappearing messages a setting that would be global for all conversations. Or I could add some kind of special syntax for the super-users. "?da here is my message" would send a disappearing message, the rest would be normal messages.

Currently, when _receiving_ a disappearing message, it should be displayed and treated like a normal message. [purple 2](https://keep.imfreedom.org/pidgin/pidgin/file/release-2.x.y/libpurple/conversation.h) has no concept of disappearing messages. purple 3 looks the same. For this reason, I cannot make received messages disappear. There are some hacks which would work on particular UIs such as Pidgin, but it does not look simple.

**Comment by hoehermann** [comment]
I felt anxious today and needed something to ease my mind. So I added experimental support for sending disappearing messages in hoehermann/purple-gowhatsapp@f9a0222.

**Update:** It behaves a bit wonky. The display regarding who did the setting is messed up. Overall, it seems to work. Can you confirm?

**Comment by hoehermann** [comment]
Closing due to lack of response.
