### ISSUE TITLE
Your username does not match the main device's ID

### ISSUE THREAD

**Issue by lazyest** [hoehermann/purple-gowhatsapp#164]
SInce yesterday I've started to get this message
Your username 'lazy' does not match the main device's ID '3752xxxxxxxx@s.whatsapp.net'. Please adjust your username.

I've updated plugin to the most recent, removed acc and tried to relogin and doesn't matter have same error. WHat else can I provide for more detailed report or maybe what can I do to fix it?

**Comment by lazyest** [comment]
just in case plugin about reporting
WhatsApp (whatsmeow)
	Author: Hermann Hoehne <hoehermann@gmx.de>
	Version: 1.12.0
	Website: https://github.com/hoehermann/libpurple-gowhatsapp
	ID String: prpl-hehoe-whatsmeow
	Loadable: Yes
	Loaded: Yes

**Comment by hoehermann** [comment]
This is a change in [1.11.0](https://github.com/hoehermann/purple-gowhatsapp/blob/whatsmeow/CHANGELOG.md#1110). 

The device ID `3752xxxxxxxx@s.whatsapp.net` is the actual identifier used by WhatsApp internally. In Pidgin, the username is used for login purposes pretty much exclusively. For other clients, however, it has been brought to my attention that in group chats there can be confusion about who user `lazy` is when the server says there is a participant with the name `3752xxxxxxxx@s.whatsapp.net`. Your own outgoing messages may be confused with incoming messages from an unknown party. 

To recover, just edit your account and copy the device ID into your username field.

**Comment by EionRobb** [comment]
There's a "purple connection set name" (or similar) function that a Prpl can use to set this without needing the user to change their login

**Comment by lazyest** [comment]
yeah, really helps to put whole phone@s.whatsapp.net as username and everything goes on

**Comment by hoehermann** [comment]
@EionRobb Indeed, `purple_conv_chat_set_nick` exists. In Pidgin, it works just fine out of the box. Unfortunately, I was unable to make it work with Spectrum and/or bitlbee (I do not remember which one had issues).

Ideally, I would use the normalization so people can have just the phone numbers without the @s.whatsapp.net. To me, using the official identifier looks like the most robust solution for now.

**Comment by brem6002** [comment]
hello, this is an old issue i know, but i still have the same error as op does, i don't know if this is the correct way to format it but i wrote it this way since from the start i got the error and still got the error anyways: "375254(rest of the phone number)@s.whatsapp.net"
