### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by Capsis** [hoehermann/purple-gowhatsapp#167]
Dear community, Dear Developer,
First of all I have used Pidgin Whatsapp fro two or three months without any issues now.
Thank You for that. This is a great product..

One day the QR failed to load.
So I reinstalled the plug-in, but after the plug-in does not show up in the list.

On Mint I have downloaded the latest version libwhatsmeow_1.12.0r241_20230628230045_amd64_ubuntu22.04.so
and copied it to /home/username/.purple/plugins
and also to /home/username/.purple/

however the plug-in does not appear in the list.

Reinstalling Pidgin does not help to solve the issue.

So what should I do?

On Windows if downloading the newest dll it is displayed in Pidgin (without an icon) as Whatsapp (whatsmenow)
and generates a QR code.
But this QR code generates an error message upon scanning.
As I do not know how to add images to Github here is the shortened text:

Invalid QR code
Please pay attention scanning a QR Code that is generated by an official Whatsapp Web/ Desktop app, Portal
If you persist experiencing issues please reload or update your app.

In Whatsapp Web on Linux with Firefox it works without issues.

**Comment by hoehermann** [comment]
Hi Capsis

Thank you for the report.

### Linux

The plug-in is supposed to go in `/home/username/.purple/plugins`. You can remove the copy from `/home/username/.purple/` to avoid confusion.

Please start pidgin from the command line with debug output enabled like this:

    pidgin -d | grep whatsmeow

Remove sensitive information and paste the output here. Or send it to [github@hehoe.de](mailto:github@hehoe.de).

### Windows

To have nice icons, unzip [whatsmeow_icons.zip](https://github.com/hoehermann/purple-gowhatsapp/files/11961502/whatsmeow_icons.zip) to your Pidgin installation, merging the `pixmaps` directory.

Unfortunately, the problem with the QR code error message does not happen on my machines. I am using Pidgin 2.14.8 on Ubuntu 22.04 with WhatsApp 2.23.9.75 on my phone. You can use Help → "Plugin Information" to confirm it is actually the current version 1.12.0 that is being used. To avoid confusion, I just deleted all old versions from the [buildbot](https://buildbot.hehoe.de/purple-whatsmeow/builds/).

**Comment by hoehermann** [comment]
Closing due to lack of response.

**Comment by hoehermann** [comment]
From the details you provided via mail, I can tell you are using a fairly old version of Linux Mint. This is the relevant line:

> plugins: ~/.purple/plugins/libwhatsmeow.so is not loadable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found

I happen to have Ubuntu installation of similar age at hand. Does [this binary](https://github.com/hoehermann/purple-gowhatsapp/files/12526082/libwhatsmeow_1.13.0r253_20230831081037_amd64_ubuntu18.04.zip) work for you?
