### ISSUE TITLE
Use libpurple to organize Desktop/Toast notifications

### ISSUE THREAD

**Issue by beadon** [hoehermann/purple-gowhatsapp#171]
Any thoughts on new support for following -- (some good and some bad ideas!) :

1. Reddit - direct messages
2. Instagram - direct messages
3. Snapchat
4. Tinder
5. Facebook Threads .. ?

And on the topic of "direct messages" I see that Windows , Mac , and to some extent GNOME are walking the path of "notifications" which are slowly creeping into the space of Pidgin.  That is to say -- the tray notifications systems getting built into operating systems today are *trying* to handle the volume of notifications from many different applications -- emails, websites, chat systems, etc.  The notifications management is failing spectacularly because it's overwhelmed and is being abused to also deliver ad messaging (see: windows, apple, google/android).

Is there an opportunity here to inject Pidgin into the notification flow and handle notifications instead of the OS ?  This is then more into the game of filtering messages / notifications intelligently.   Combining this WITH chat hands more control to the user.  And so -- are these OS-notification systems just another libpurple plugin ?

Thoughts ?

**Comment by hoehermann** [comment]
Hi beadon

I assume you are writing about [Desktop Notifications](https://wiki.archlinux.org/title/Desktop_notifications). On Windows, they are called [Toast Notifications](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/toast-notifications-overview). I have no idea what the MacOS terminology is.

While there are APIs to [read notifications](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener), I do not know of any way to "hijack" or "re-route" notifications on Windows. More research would need to be done. libpurple is quite flexible. I expect you could feed the notifications into Pidgin, possibly even assign them to the users, protocols and conversations. However, it is way out of scope of this project and I do not want to start a project in this direction.

Kind Regards
Hermann

**Comment by beadon** [comment]
Yep, just capturing some ideas here.  The sprawl of notifications is intense.
