### ISSUE TITLE
Unable to compile on aarch64 arch anymore

### ISSUE THREAD

**Issue by pinoverclock** [hoehermann/purple-gowhatsapp#176]
I'm unable to make 1.13 compile on aarch64 (Archlinux 6.4.1):

I'm using the [AUR ](https://aur.archlinux.org/packages/purple-gowhatsapp-git) package

`[100%] Linking C shared library libwhatsmeow.so`
`/usr/bin/ld: ../go/purple-go-whatsapp.a(go.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol 'crosscall2' which may bind externally can not be used when making a shared object; recompile with -fPIC`
`/usr/bin/ld: DWARF error: line info data is bigger (0x337d9403) than the space remaining in the section (0x19adc9)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x1bf0400) than the space remaining in the section (0x1967e7)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x637063a) than the space remaining in the section (0x188ac7)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x88af0a14) than the space remaining in the section (0x188a0b)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x3b063706) than the space remaining in the section (0x188371)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x6b03606) than the space remaining in the section (0x18029b)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x12045b7c) than the space remaining in the section (0x180069)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x38063706) than the space remaining in the section (0x17fecb)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x3120433) than the space remaining in the section (0x17fb41)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x65e3808) than the space remaining in the section (0x12712d)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x5990306) than the space remaining in the section (0x126fb3)`
`/usr/bin/ld: DWARF error: unhandled .debug_line version 0`
`/usr/bin/ld: DWARF error: line info data is bigger (0xfb79033c) than the space remaining in the section (0x11e701)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x6370639) than the space remaining in the section (0x11d861)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x30b0400) than the space remaining in the section (0x117a69)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x3019d04) than the space remaining in the section (0xdac67)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x65f06ab) than the space remaining in the section (0xb5fc3)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x26032204) than the space remaining in the section (0xa8f09)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x6380637) than the space remaining in the section (0x9ad27)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x83063989) than the space remaining in the section (0x8860f)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x3063706) than the space remaining in the section (0x518df)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x6383706) than the space remaining in the section (0x4fd8f)`
`/usr/bin/ld: DWARF error: line info data is bigger (0x3063706) than the space remaining in the section (0x46e69)`
`../go/purple-go-whatsapp.a(go.o): in function 'runtime/cgo.set_crosscall2.abi0':
go.go:(.text+0x2c69f8): dangerous relocation: unsupported relocation`
`collect2: error: ld returned 1 exit status`
`make[2]: *** [src/c/CMakeFiles/whatsmeow.dir/build.make:370: src/c/libwhatsmeow.so] Error 1`
`make[1]: *** [CMakeFiles/Makefile2:223: src/c/CMakeFiles/whatsmeow.dir/all] Error 2`
`make: *** [Makefile:156: all] Error 2`

**Comment by hoehermann** [comment]
`-fPIC` is a gcc option which [should be enabled by default](https://cmake.org/cmake/help/v3.18/prop_tgt/POSITION_INDEPENDENT_CODE.html). I have no idea why this is not or no longer the case for you.

**Comment by pinoverclock** [comment]
I'm already using -fPIC gcc option for both CFLAGS and CXFLAGS, seems that the issue it's related to my distcc setup...

Thank you for pointing me the right direction, closing

**Comment by pinoverclock** [comment]
I'm already using -fPIC gcc option for both CFLAGS and CXXFLAGS, seems that the issue it's related to my distcc setup...

Thank you for pointing me the right direction, closing
