### ISSUE TITLE
Problem building on linux mint at 'cmake --build .' step 

### ISSUE THREAD

**Issue by zoltan-dulac** [hoehermann/purple-gowhatsapp#179]
I seem to have a problem building on my Linux Mint laptop on the final step (i.e. `cmake --build .`).  I am not familiar with go at all, so I am a little stumped.  Any idea what is wrong here?  Here is the output of the command:

```
~/git/purple-gowhatsapp/build$ cmake --build .
[ 12%] Built target purple-dummy
[ 16%] Updating go modules...
go: finding go.mau.fi/whatsmeow latest
github.com/hoehermann/purple-gowhatsapp/src/go imports
	go.mau.fi/whatsmeow/binary/proto imports
	embed: malformed module path "embed": missing dot in first path element
github.com/hoehermann/purple-gowhatsapp/src/go imports
	golang.org/x/net/http2 imports
	io/fs: malformed module path "io/fs": missing dot in first path element
github.com/hoehermann/purple-gowhatsapp/src/go imports
	go.mau.fi/whatsmeow imports
	golang.org/x/crypto/curve25519 imports
	crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element
make[2]: *** [src/go/CMakeFiles/purple-go-whatsapp.dir/build.make:97: /home/XXX/git/purple-gowhatsapp/src/go/go.mod] Error 1
make[2]: *** Deleting file '/home/XXX/git/purple-gowhatsapp/src/go/go.mod'
make[1]: *** [CMakeFiles/Makefile2:197: src/go/CMakeFiles/purple-go-whatsapp.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by hoehermann** [comment]
Thank you for the report. Which go version are you using? Maybe it is too old. This project needs at least go 1.20 (the google version, the gcc version is not quite there, yet).

**Comment by zoltan-dulac** [comment]
Thanks @hoehermann for the tip.  That seemed to do the trick. For anyone reading this thread trying to resolve this issue, all I did [was follow the instructions here](https://gist.github.com/nikhita/432436d570b89cab172dcf2894465753), except I used `sudo apt remove golang-go` to remove the version of go I installed with `apt` previously.
