### ISSUE TITLE
Reactions show as blanks

### ISSUE THREAD

**Issue by UnitedMarsupials** [hoehermann/purple-gowhatsapp#186]
This may be some sort of local (mis)configuration here, but the reaction-messages I'm getting do not show the actual reaction :(

Once I copy/paste the reaction-message elsewhere -- such as into this browser, I see the emojis:

> Such and Such : reacted with 😂 to message "Вочевидь, " from 24 Jan 24 14:12 EST.

But in the pidgin-window the above smiley -- between the words "with" and "to" -- appears blank. Is it because my default font does not have renderings for the emoji part of UTF8? Can the plugin switch the font for those few characters -- as the browser seems to be doing?

Or is this something Pidgin itself is supposed to do (and does not)?

**Comment by EionRobb** [comment]
If you're on windows, pidgin won't show emoji without using a smiley theme as a workaround eg pidgin-emojione-smiley-theme, but if you're on Linux that sounds like it might maybe also work as a workaround?

**Comment by UnitedMarsupials** [comment]
> If you're on windows

No, I'm using an X11 desktop -- XFCE4 to be more specific.

My own smilies are sent using the character-combinations, for example: ":-D"

> pidgin won't show emoji without using a smiley theme as a workaround eg pidgin-emojione-smiley-theme, but if you're on Linux that sounds like it might maybe also work as a workaround?

I have the default smiley theme enabled already -- the "Hylke Bons". But, I think, that only matters for translating the character-combinations into icons locally. When the text contains an emoji expressed as a UTF8 character, Pidgin shows a blank...

**Comment by EionRobb** [comment]
Yeah the emoji smiley themes also translate unicode emoji characters too

**Comment by hoehermann** [comment]
I just tried reacting with that very emoji.

1. The "symbola" smiley theme from https://github.com/stv0g/unicode-emoji.
2. No smiley theme.
3. Smiley theme by "Hylke Bons".

![a](https://github.com/hoehermann/purple-gowhatsapp/assets/838331/1d80520a-2463-4518-ac22-d3a1e2afbdcc)

1. The emoji glyph is replaced by the smiley.
2. It looks like in case of "no theme", GTK tries to render the glyph with any font available. On Ubuntu, I have `fonts-noto-color-emoji` installed, so I guess that's it. 
3. I suspect, the smiley theme by "Hylke Bons" does not contain a smiley for that particular emoji. GTK might fall back to the method described above.

Can you install `fonts-noto-color-emoji` (or an equivalent) and see if that improves the situation for you?

**Comment by UnitedMarsupials** [comment]
> Can you install fonts-noto-color-emoji and see if that improves the situation for you?

Yay, that helped. Added the [x11-fonts/noto-emoji port](https://www.freshports.org/x11-fonts/noto-emoji), restarted Pidgin, and now they work. Don't know, why that font was not necessary for the browser to show the pictograms, but, perhaps, I don't need to know.

**Comment by hoehermann** [comment]
Thank you for letting us know it works that way.
