### ISSUE TITLE
QR Code appearing all scrambled with Spectrum2 and Gajim

### ISSUE THREAD

**Issue by slmc-tech** [hoehermann/purple-gowhatsapp#191]
Hi there, I am really new to this and I cannot tell if this is an actual defect or not. 

We are using spectrum2 with Openfire and Gojara and when a client tries to login the qr code is not properly formatted and cannot be scanned. Our client is Gajim.

I have tried setting the qrcode-size = 0 to circumvent this but instead i am seeing a server error message.
Is there any way that you can test this or even better is there any logging that I can activate through spectrum that will help with detecting the issue?

I thank you in advance.

**Comment by hoehermann** [comment]
Thank you for the question.

In theory, both Spectrum and Gajim should honour the line-breaks. However, in text-only-mode, the QR-code is supposed to be rendered on a terminal – or at least with a monospace font. Can you set Gajim to a monospace font? You can also try to copy and paste the textual QR code into a terminal (running `cat` or something).

I do not know how to make images work with Spectrum. Maybe another Spectrum user can help you.

**Comment by slmc-tech** [comment]
<img width="733" alt="WhatsApp QRCode Rendering" src="https://github.com/hoehermann/purple-gowhatsapp/assets/102043357/9206098a-9611-486c-92d5-07aadd159724">
Thank you for taking the time to look into this. To be honest I have no idea how to do what you are suggesting. I am attaching a screenshot of how the QR is rendered in case this may be of any help. Maybe someone has seen this before..
Thanks,

**Comment by hoehermann** [comment]
You can set the font to a "Monospace" font. On Linux Pidgin uses the default GTK. You can configure it via the font section in the "Appearance" settings tool. On my system, it looks like this:
![logon](https://github.com/hoehermann/purple-gowhatsapp/assets/838331/a5db7434-d76f-470c-91f3-c5985ad7ebaa)
Although there are some horizontal lines, the WhatsApp App my phone can scan it.

Alternatively, you can copy the authentication string (highlighted with the blue selection) and paste it into any tool that turns plain text into a QR code and scan that. https://www.the-qrcode-generator.com/ works fine (no affiliation, just the first search result).

**Comment by slmc-tech** [comment]
Hi Again, I actually may have found a workaround to this. 
Not sure if this is going to help others but apparently the QR code is coming through properly in the console. 
Gajim has an option to view XML console. From there you have two tabs a Protocol tab and a Log tab. When we look at the protocol tab we will see that the QR code appears as you would expect and is scannable. So it is coming from the service properly.
Thank you once again for taking the time to look into this.

**Comment by hoehermann** [comment]
Thank you for telling about the workaround. This will surely be helpful in the future.
