### ISSUE TITLE
Client outdated (405) connect failure

### ISSUE THREAD

**Issue by vsevjednom-cz** [hoehermann/purple-gowhatsapp#198]
Hi all, purple-gowhatsapp is amazing but this problem started 2 days ago.

420NUMBER@s.whatsapp.net denied:
Client outdated (405) connect failure

I tried to config account again but it not works.

I tried to run this:
pidgin -d | grep whatsmeow:
(09:08:17) plugins: probing /home/.../.purple/plugins/libwhatsmeow.so
09:09:05) whatsmeow: No proxy set in purple. The go runtime might pick up the https_proxy environment variable regardless.
(09:09:06) whatsmeow: [Database] sqlite3 connecting to file:/home/.../.purple/whatsmeow.db?_foreign_keys=on&_busy_timeout=3000
(09:09:06) whatsmeow: [Client/Socket] Dialing wss://web.whatsapp.com/ws/chat
(09:09:06) whatsmeow: [Client/Socket] Frame websocket read pump starting 0xc000178bb0
(09:09:10) whatsmeow: [Client/Recv] <failure location="odn" reason="405"/>
(09:09:10) whatsmeow: recieved error (subtype 1) for account 0x58eb60910b80 remote (null) (isGroup 0) sender (null) (alias (null), fromMe 0) sent 0: [Client] Client outdated (405) connect failure
(09:09:10) whatsmeow: [Handler] Event type not handled: &events.ClientOutdated{}
(09:09:10) whatsmeow: [Client/Socket] Frame websocket read pump exiting 0xc000178bb0

I don't know where is a problem. I'm using Ubuntu.

**Comment by hoehermann** [comment]
The version has been updated in https://github.com/tulir/whatsmeow/commit/051606b388f61ee4f88ddd49ac49266beef26240. That was a month ago. Did you update since then? There is a binary for Ubuntu 22.04 at https://buildbot.hehoe.de/purple-whatsmeow/builds/libwhatsmeow.so. I plan to upgrade to 24.04 in August.

**Comment by vsevjednom-cz** [comment]
Wow, amazing! Thank you!
