### ISSUE TITLE
  CMake 3.18 or higher is required

### ISSUE THREAD

**Issue by lazyest** [hoehermann/purple-gowhatsapp#201]
reqs are telling us it requires cmake 3.8 but all we have

  CMake 3.18 or higher is required.  You are running version 3.16.3

ubuntu 20.04 is still pretty fresh, cmon!

**Comment by hoehermann** [comment]
Hi @lazyest 

Thank you for the comment. For the win32 build, I need features from CMake 3.18. That is why I did not test with older versions.

Feel free to adjust the version requirement in the `CMakeList.txt` and let me know if it works on Ubuntu 20.04.

Kind Regards
Hermann

**Comment by hoehermann** [comment]
Does building the plug-in work with CMake 3.16 on Ubuntu 20.04?

**Comment by hoehermann** [comment]
Closing due to lack of answer. In case you can confirm building with CMake 3.16 actually works, please let me know.

**Comment by lazyest** [comment]
sorry for late answer, it was build successfully (need to change version twice)

**Comment by hoehermann** [comment]
Thank you. I want to find out if I can lower the CMake version requirement to 3.16 and conditionally require 3.18 only if the environment is Windows.

**Comment by hoehermann** [comment]
Implemented in 42eedbc.
