### ISSUE TITLE
libpurple 2.13 / Ubuntu 20.04

### ISSUE THREAD

**Issue by lazyest** [hoehermann/purple-gowhatsapp#202]
Seems like on pidgin 2.13 plugin stopped working, I've built recent one and it dissapeared from plugins list ;(

**Comment by hoehermann** [comment]
Hi @lazyest 

Thank you for the report. Please execute

    pidgin -d 2>&1 | grep whatsmeow | tee pidgin_debug.log

and post the debug output here (after redacting sensitive personal information).

Kind Regards  
Hermann

**Comment by pkar70** [comment]
Probably same problem as mine - "connecting" forever (no connect).

**Comment by pavolgaj** [comment]
I had the same problem. Updating libwhatsmeow to the latest version fixed it.

**Comment by pkar70** [comment]
Yes, it fixes problem. Thanx.

**Comment by hoehermann** [comment]
Reported fixed. @lazyest in case the issue still persists for you, feel free to re-open this issue.

**Comment by lazyest** [comment]
well, I've compiled recent release, fixed it for old cmake version. But now I have plugin inactive because of 
plugins: /usr/lib/purple-2/libwhatsmeow.so is not loadable: undefined symbol: g_memdup2

**Comment by lazyest** [comment]
just in case, binary so made for 22.04 returned 

plugins: /usr/lib/purple-2/libwhatsmeow_1.14.0r278_20240507080416_amd64_ubuntu22.04.so is not loadable: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib/purple-2/libwhatsmeow_1.14.0r278_20240507080416_amd64_ubuntu22.04.so)

this is complete understood

**Comment by hoehermann** [comment]
> /usr/lib/purple-2/libwhatsmeow.so is not loadable: undefined symbol: g_memdup2

That is weird. [g_memdup2](https://docs.gtk.org/glib/func.memdup2.html) is available in glib 2.68 and newer. I have a version check with a fall-back in place [here](https://github.com/hoehermann/purple-gowhatsapp/blob/e821414f57079e6bfa08d01b7e9cc56ecab4d69c/src/c/bridge.c#L84), so a custom build on Ubuntu 20.04 still should work.

**Comment by lazyest** [comment]
any other suggestions? ;) how to possibly debug it? i'm not very familiar with dev environment honestly

**Comment by lazyest** [comment]
for me it looks like check is somehow not working maybe?

**Comment by lazyest** [comment]
Is it better to createn new issue about 20.04 compatibility?

**Comment by lazyest** [comment]
I've just recompiled it again and still have

(10:19:33) plugins: probing /usr/lib/purple-2/libwhatsmeow.so
(10:19:33) plugins: /usr/lib/purple-2/libwhatsmeow.so is not loadable: undefined symbol: g_memdup2

what can I maybe customly try?

**Comment by lazyest** [comment]
or can you somehow build binary for 20.04 to be sure everything is building correct?

**Comment by hoehermann** [comment]
Hi. I just tried with the regular steps (details [here](https://github.com/hoehermann/purple-gowhatsapp/blob/whatsmeow/.github/workflows/linux.yml)):

    git clone --recurse-submodules https://github.com/hoehermann/purple-gowhatsapp
    cd purple-gowhatsapp
    cmake -B build -S .
    cmake --build build

It produced [this](https://github.com/user-attachments/files/16863540/20.04.zip) result. Unfortunately, I do not have time to verify if it works right now.

**Comment by lazyest** [comment]
Couldn't find any package by glob 'libgdk-pixbuf-2.0-0'
lazy@lazynote:~$ sudo apt -f install libgdk-pixbuf2.0-
libgdk-pixbuf2.0-0       libgdk-pixbuf2.0-bin     libgdk-pixbuf2.0-common  libgdk-pixbuf2.0-dev     libgdk-pixbuf2.0-doc     
lazy@lazynote:~$ sudo apt -f install libgdk-pixbuf2.0-0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgdk-pixbuf2.0-0 is already the newest version (2.40.0+dfsg-3ubuntu0.5).


but anyhow after manual unpack 

(14:43:21) plugins: /usr/lib/purple-2/libwhatsmeow.so is not loadable: undefined symbol: g_memdup2

**Comment by lazyest** [comment]
another super weird thing detected :) I've broke my head trying to resolve it by the way
after provided .so put into /usr/lib/purple directory it wasn't loaded by pidgin but caused it to segfault after near minute of work :) removing .so resolved issue

**Comment by hoehermann** [comment]
While cleaning up, I found an Ubuntu 20.04 installation and tried it myself. It turns out that while I did in fact put that GLib version check in the code, it was not in the correct place. To be honest, I do not know why the compiler even accepts the code that way, but here we are. Thank you for insisting on the issue. Have [this binary](https://github.com/user-attachments/files/16935530/libwhatsmeow_ubuntu20.04_amd64.zip) which for me is working on Ubuntu 20.04. I also updated the code in default branch. :)

**Comment by hoehermann** [comment]
Github pulled the support for Ubuntu 20.04. 🙁 The binaries provided are built against Ubuntu 22.04.

**Comment by lazyest** [comment]
and now we are unable to build it again ;(
(11:59:20) plugins: probing /usr/lib/purple-2/libwhatsmeow.so
(11:59:20) plugins: /usr/lib/purple-2/libwhatsmeow.so is not loadable: undefined symbol: g_memdup2

**Comment by hoehermann** [comment]
Unable to build or unable to run the binary supplied in the github releases? If you want to use this plug-in with GLib older than version 2.68 (Ubuntu 20.04 "focal" has GLib 2.64.2), you can build the plug-in yourself. Feel free to add a comment if you want help with that.

**Comment by lazyest** [comment]
I've build it but its not running, just like I've described and just like it was before

**Comment by hoehermann** [comment]
For you, I double checked and build on Ubuntu 20.04 again (via docker):

```
sudo apt update
sudo apt install --no-install-recommends libpurple-dev pkg-config make gcc libgdk-pixbuf2.0-dev libopusfile-dev git wget ca-certificates
cd /tmp/
wget https://go.dev/dl/go1.25.1.linux-amd64.tar.gz
tar xf go1.25.1.linux-amd64.tar.gz 
PATH=/tmp/go/bin:$PATH
git clone --recurse-submodules https://github.com/hoehermann/purple-gowhatsapp purple-whatsmeow
cd purple-whatsmeow/
make
cp libwhatsmeow.so /usr/lib/purple-2/
```

It works. [libwhatsmeow_amd64_ubuntu2004.so.zip](https://github.com/user-attachments/files/20533143/libwhatsmeow_amd64_ubuntu2004.so.zip)

**Comment by lazyest** [comment]
possibly I've followed some older README but yes, your .so is working fine, thanks ;) sorry for bothering but it was a pain for me

**Comment by lazyest** [comment]
its me again

-- OPUSFILE_LINK_LIBRARIES: /usr/lib/libopusfile.so
CMake Error at scripts/go.cmake:1 (cmake_minimum_required):
  CMake 3.20 or higher is required.  You are running version 3.16.3
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)


-- Configuring incomplete, errors occurred!

thats all? no more whatsapp for me, right?

**Comment by hoehermann** [comment]
For your convenience, I added a Makefile for use with the `make` command. No need for cmake.

**Comment by lazyest** [comment]
no luck either :(

/usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
  271 | struct _GParameter /* auxiliary structure for _setv() variants */
      |        ^~~~~~~~~~~
make: *** [Makefile:19: libwhatsmeow.so] Error 1

maybe you can just build more recent binary for 20.04 if your building stand is still operational?

**Comment by hoehermann** [comment]
```
/usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
271 | struct _GParameter /* auxiliary structure for _setv() variants */
```
These are just the last two lines of a longer warning message.

The compilation fails because Ubuntu 20.04 comes with purple version 2.13.0 from 2018 and does not yet support the `get_cb_alias` callback. I attached a build without expecting that feature. Enjoy.

[libwhatsmeow_amd64_ubuntu2004.so.zip](https://github.com/user-attachments/files/22511174/libwhatsmeow_amd64_ubuntu2004.so.zip)
