### ISSUE TITLE
Video Notes Support

### ISSUE THREAD

**Issue by Juliaria08** [hoehermann/purple-gowhatsapp#205]
At least properly receive and store them.

Currently nothing happens.

I'm not sure if this is purple-gowhatsapp or whatsmeow. I think whatsmeow so I'll ask here first as I'm not too sure, and that way this can be supported here after upstream supports it? (but I think they'll probably just add it as another DownloadableMessage so maybe I shouldn't make this here?

**Comment by hoehermann** [comment]
Thank you for the request. Sounds reasonable. I did not even know of this message type. Handling it is probably not a big deal. No idea when I will implement it, though.

**Comment by hoehermann** [comment]
Implemented in 2239f3a.
