### ISSUE TITLE
Feature-Request Option for adding MessageID to the end of messages

### ISSUE THREAD

**Issue by Juliaria08** [hoehermann/purple-gowhatsapp#206]
Add toggle that when enabled puts the messageID of a message at the end of it, (this could later be used to allow reactions and edits easily, as you already have the message's ID (you can copy paste it from the logs))

**Comment by hoehermann** [comment]
Thank you for the suggestion. Is plain-text okay? I am not sure if I can put it into HTML markup.

**Comment by Juliaria08** [comment]
Yeah, I think it's better as plaintext, (maybe put it with a prefix and suffix to allow automated systems to extract it easily?

**Comment by Juliaria08** [comment]
Thanks.
The feature works flawlessly.

**Comment by Juliaria08** [comment]
> Thanks. The feature works flawlessly.

Wait, I noticed that images don't get their message ID shown (at least when they don't have a comment, and the what to do with incoming images is set to: Do both)

**Comment by Juliaria08** [comment]
Well, now I can't reproduce it now, weirdly?
