### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Krukosz** [hoehermann/purple-gowhatsapp#21]
Hi,

I'm trying to compile binary on Windows x64 and i'm receiving such errors:

```
`d:\www\purple-gowhatsapp-master>go build -buildmode=c-archive -o purplegwa.a pur
plegwa.go
# command-line-arguments
.\purplegwa.go:129:17: handler.sendMediaMessage undefined (type *waHandler has n
o field or method sendMediaMessage)
.\purplegwa.go:230:9: handler.downloadMessage undefined (type *waHandler has no
field or method downloadMessage)
.\purplegwa.go:235:9: handler.downloadMessage undefined (type *waHandler has no
field or method downloadMessage)
.\purplegwa.go:239:9: handler.downloadMessage undefined (type *waHandler has no
field or method downloadMessage)
.\purplegwa.go:243:9: handler.downloadMessage undefined (type *waHandler has no
field or method downloadMessage)
.\purplegwa.go:340:17: undefined: generateFilepath
.\purplegwa.go:341:12: handler.storeDownloadedData undefined (type *waHandler ha
s no field or method storeDownloadedData)`
```

What would be a problem?

**Comment by hoehermann** [comment]
The command looks incomplete. It is one source file short. [The Makefile](https://github.com/hoehermann/purple-gowhatsapp/blob/e99cddadc43cf1ed9e8d175b7df591cc58d040e5/Makefile.mingw#L46) executes

    go build -buildmode=c-archive -o purplegwa.a purplegwa.go purplegwa-media.go

**Comment by Krukosz** [comment]
Ok, now it compiled to .a file.
I'm on creating dev environment on Windows.
@EionRobb , how did you made the development environment? I followed steps from [Pidgin Wiki](https://developer.pidgin.im/wiki/BuildingWinPidgin) using Cygwin64, but still this plugin doesn't see libpurple development headers

**Comment by hoehermann** [comment]
Unrelated to the question for assistance in development environment set-up, I am closing this issue, since it does not describe a problem with the plug-in implementation itself.
