### ISSUE TITLE
go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20

### ISSUE THREAD

**Issue by lazyest** [hoehermann/purple-gowhatsapp#213]
fresh clone of repo on 22.04, have

purple-gowhatsapp/build$ cmake --build .
[ 16%] Built target purple-dummy
[ 16%] Updating go modules...
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
make[2]: *** [src/go/CMakeFiles/purple-go-whatsapp.dir/build.make:96: ../src/go/go.mod] Error 1
make[2]: *** Deleting file '../src/go/go.mod'
make[1]: *** [CMakeFiles/Makefile2:197: src/go/CMakeFiles/purple-go-whatsapp.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by hoehermann** [comment]
Thank you for the report. That information is outdated, actually. Two months ago, the back-end library whatsmeow switched to go 1.22: https://github.com/tulir/whatsmeow/commit/20b526a29c137a312ef29e4925d748ae144a3da7.

The good news is that the go environment is pretty self-contained. Just download a recent version for your platform from https://go.dev/dl/. Decompress it anywhere. I typically out it in `/opt/go`. Then run cmake with `-DCMAKE_Go_COMPILER=/opt/go/bin/go` for cmake to prefer the specific version over the system default.

Good luck!

**Comment by hoehermann** [comment]
Since there was no response, I assume this issue has been overcome. If I am mistaken, feel free to re-open this issue.
