### ISSUE TITLE
insert image option is greyed out

### ISSUE THREAD

**Issue by pGeek64** [hoehermann/purple-gowhatsapp#214]
i just installed this plugin from aur `purple-gowhatsapp-git` and the insert > image is greyed out 
![image](https://github.com/user-attachments/assets/bc997b8a-ac5f-4298-ab19-f95c3a6421e8)
am i doing anything wrong

**Comment by pGeek64** [comment]
nevermind it was actually in send file but it would be nice if it were there on the insert option ig

**Comment by hoehermann** [comment]
Thank you for the suggestion. Unfortunately, when allowing in-line images, I would need to break the outgoing message apart into multiple messages. It is doable, but quite a chore. I described the details in #210.
