### ISSUE TITLE
Tutorial for Build by myself?

### ISSUE THREAD

**Issue by GRxRedZero** [hoehermann/purple-gowhatsapp#22]
Can u write a little introduction to build manually this plugin?
It doesn work for me on Ubuntu 18.04, every other purple-plugin works.

**Comment by hoehermann** [comment]
Download the sources, enter the directory, execute `make`. In case of specific problems, please include the terminal output. I do not do further tutoring.

**Comment by GRxRedZero** [comment]
I already did. But what can I do with the *.a file?

**Comment by hoehermann** [comment]
`purplegwa.a` is just a by-product. `libgowhatsapp.so` is the shared library you can put in you Pidgin's plug-ins directory.

**Comment by GRxRedZero** [comment]
Okay thank you I did it. Problem to use this plugin is still there.
[https://github.com/hoehermann/purple-gowhatsapp/issues/20](url)
