### ISSUE TITLE
Connection state is not displayed reliably

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/purple-gowhatsapp#24]
This prpl's connection state is not displayed properly. Errors are sometimes disregarded. This lead to Pidgin end-user confusion as seen at #19 and #20. spectrum2 is affected too, as seen at #5 .

This prpl calls

    purple_connection_set_state(pc, PURPLE_CONNECTION_CONNECTING);

and

    purple_connection_set_state(pc, PURPLE_CONNECTED);

(in this order). Yet I never saw the "connecting" state regarded in Pidgin's UI.

This prpl calls

    purple_connection_set_state(pc, PURPLE_DISCONNECTED);

when the connection is closed by user request.

All other disconnects happen implicitly due to errors reported by

    purple_connection_error(pc, PURPLE_CONNECTION_ERROR_OTHER_ERROR, "error description");

.

I do not know what I am doing wrong. It looks I need help by a purple veteran. @EionRobb, can you give me any pointers on this one?

**Comment by EionRobb** [comment]
Generally, you shouldn't ever set the `_DISCONNECTED` state, the error handling system and the account disconnect/close system will do that for you.

The `_CONNECTING` state is normally only ever seen in the Accounts list, although it can show in the Available/Away/Offline status dropdown in the buddy list if you use `purple_connection_update_progress()` to say that it's only at eg step one of three.

When you say "the state is not displayed correctly" where are you expecting it to be displayed?

**Comment by hoehermann** [comment]
I am grateful for your response.

Ok, I want to remove the call setting the `_DISCONNECTED` state. Thank you.

I am aware, the drop-down state selector shows the user-requested state and not the current state. Therefore, I am expecting the `_CONNECTING` state to be visible in the status drop-down (by displaying a spinner).  
More importantly, I want errors to be displayed consistently. Right now, an error may close the connection, but the end-user does not realize that the connection has been closed. The user would need to check the list in the accounts menu.  
At least, this is what I can observe with commits prior to 6d997ae.This is what happened to the user in #19 – until [you helped by pointing out](https://github.com/hoehermann/purple-gowhatsapp/issues/19#issuecomment-517009113) the connection was in fact never made. Folks at the spectrum2 IRC told me they too are affected: The connection is allegedly regarded online when in fact an error occurred during log-in.

On the other hand, I might be overthinking this. Things are probably working as intended and it all boils down to end-user error.

**Comment by hoehermann** [comment]
I have not observed this problem with the whatsmeow re-write. Please re-open this issue in case the problem pops up again.
