### ISSUE TITLE
only 1 connection at a time?

### ISSUE THREAD

**Issue by brianjmurrell** [hoehermann/purple-gowhatsapp#25]
I read that this plugin only allows one connection to whatsapp at a time, including the connection from your phone.

Is that a whatsapp limitation or just this plugin?  I.e. could I connect to whatsapp from two phones successfully or will that also limit me to only one connection?  Does it refuse the second one or does the second connection boot the first one?

**Comment by hoehermann** [comment]
It was a limitation in an early version. Where do you read that? I may have forgotten to update the description. You can have one Pidgin connect to multiple phones (although not tested by me – I only have one phone). Bear in mind that the official WhatsApp app allows one connection only. So you can connect to your phone either with the normal browser _or_ the plug-in.

**Comment by hoehermann** [comment]
I do not maintain RPM packages. Must have been someone else.

Indeed, this plug-in uses the WhatsApp **Web** API (connects to the phone). There is no reliable method of connecting to WhatsApp's servers directly. yowsup exists, but is [currently blocked](https://github.com/tgalal/yowsup/issues/2829) by WhatsApp. As far as I am concerned, this happens on a regular basis.

**Comment by brianjmurrell** [comment]
So the app on the phone starts up an HTTP server and exposes an API?

**Comment by hoehermann** [comment]
It is a bit more awkward than that, I am afraid. I do not know the details for sure, but it is somewhat like this: The official WhatsApp client on the phone forwards the (allegedly encrypted) messages to a WhatsApp server. The server exposes an API. My plug-in connects to the server using [go-whatsapp](https://github.com/Rhymen/go-whatsapp), which is written by Lucas Engelke. The server then forwards the messages to the plug-in.

For a response, the plug-in sends a message to the WhatsApp server, which then forwards the message to the official WhatsApp client on the phone, which then forwards the message to another  WhatsApp server which then sends the message to the recipient. Totally straight forward, if you ask me. ;)

**Comment by brianjmurrell** [comment]
Aye karumba!

**Comment by hoehermann** [comment]
Closing due to age and inactivity.
