### ISSUE TITLE
Group chats don't show who is saying what

### ISSUE THREAD

**Issue by brianjmurrell** [hoehermann/purple-gowhatsapp#26]
In a group chat, everything said is reported as coming from the group name, not the name of the person in the group that said what was said.

I am sure you could imagine how difficult that makes following group chats.

**Comment by hoehermann** [comment]
I know. I never figured out how to do group chats (Pidgin keeps crashing on me). :(

**Comment by hoehermann** [comment]
@brianjmurrell Version 0.3.2 includes the additions of commit 09d8608. Group chats are still no proper group chats, but the participant's number (or name/alias, if you added them to Pidgin's buddy list) should be displayed. I hope this helps.

**Comment by brianjmurrell** [comment]
@hoehermann I just noticed this as I was confirming the fix in #61 was fixing #38 also.

I can confirm, I do see the identity of the group member sending each message, so this is a huge step up.

Could you expand on:
> Group chats are still no proper group chats

?

Just wondering what they are missing.

**Comment by hoehermann** [comment]
> I just noticed this as I was confirming the fix in #61 was fixing #38 also.

That is wonderful news. Thank you.

> Just wondering what they are missing.

Proper Pidgin chats show the full list of participants. Also, you can join and leave them.

But implementing group chats properly is quite tedious, as I learned from my other plug-in [purple-signald](https://github.com/hoehermann/libpurple-signald/commit/2141f2e). As a result, I consider the current state "90% there, works for me" and I want to keep it this way for now. :)

**Comment by brianjmurrell** [comment]
> That is wonderful news. Thank you.

Well, I haven't actually confirmed it yet.  I've only been running with the latest master for a day or two now.  Even before the memory management fixes I could run for several days without a crash.  So it's a bit soon to declare victory yet.

**Comment by brianjmurrell** [comment]
> Proper Pidgin chats show the full list of participants. Also, you can join and leave them.

Ah, yes.  I hadn't noticed that was lacking.

**Comment by luqven** [comment]
I realize this is a big ask, but if @EionRobb could be so kind as to either:

- 1 write up a windows binary building doc or 
- 2 comment / attach a build that includes this latest fix on master that would be just incredible 🙏🏼

I'd be happy to help building those, just don't have much experience with `.dll` and makefiles.

**Comment by hoehermann** [comment]
Nightly builds are are available at https://buildbot.hehoe.de/purple-gowhatsapp/builds/?C=M;O=D. This also automatically releases new versions if go-whatsapp (library included) is updated.
