### ISSUE TITLE
Bitlbee: saving authentication

### ISSUE THREAD

**Issue by drwggm** [hoehermann/purple-gowhatsapp#27]
Hi,

I was able to get the plugin to work with purple/bitlbee, but have been having issues getting it to save the credentials after restarting the server.

e.g., add whatsapp account, do the qr code thing, account is active -- can chat.  run `save` from the &bitlbee command channel.  The account shows up in the user.xml file within the bitlbee conf directory, but nothing shows up in the purple directory other than the `login` file used for the qr code.

Is there a trick to getting the credentials to persist across bitlbee restarts?

Thanks

**Comment by hoehermann** [comment]
I am using the function `purple_account_set_string` to store the login information in the account's persistent data section and `purple_account_get_string` to retrieve them. Looking at bitlbee's code, I cannot tell for sure if these functions are properly supported bitlbee. I'll have ask the bitlbee developers for pointers.

**Comment by hoehermann** [comment]
Folks at the Bitlbee irc channel tell me you are better off using alternative solutions. Example given was https://git.theta.eu.org/sms-irc.git/about/.

**Comment by EionRobb** [comment]
bitlbee (and spectrum2 and telepathy-haze) have their own settings storage and create their accounts.xml on the fly when connecting to an account, they don't persist anything set in `purple_account_set_string`

bitlbee does offer one way to provide a single value back up using a signal https://github.com/bitlbee/bitlbee/blob/18a0f99732b1cb96cbb06763561c7a2526535a67/protocols/purple/purple.c#L1763-L1770 eg  https://github.com/EionRobb/purple-hangouts/blob/e8c8088692b37a8b0bb2401bcbca8e6b2cf87d5e/hangouts_auth.c#L70
