### ISSUE TITLE
Installation Wiki

### ISSUE THREAD

**Issue by radasbona** [hoehermann/purple-gowhatsapp#3]
Hi,
Thanks for your work. i would like to test is, but can't find a installation manual. 
(UbuntuMate 18.04)

**Comment by hoehermann** [comment]
Download [the binary](https://ssl.hehoe.de/temp/libgowhatsapp_x86_64.so) or compile it yourself using the supplied Makefile. Place the binary it in the "plugins" directory of your Pidgin directory. `~/.purple/plugins/` is the per-user default.

**Please be aware that this is a development build.** It is lacking important features and may not work as good as you would like it.

**Comment by radasbona** [comment]
Thanks. I test it next week when I'm back at home.

Sure. I like testing new plugins.

**Comment by radasbona** [comment]
Works really fine. That's all what i need, thank you. 
Nice idea to use the wa.web api, i hope you will get no angry message from these walled garden fanboys.

**Comment by hoehermann** [comment]
Thank you. But I did not actually reverse-engineer the protocol nor implement the library. Credit goes to Lucas "Rhymen" Engelke and the other folks providing [go-whatsapp](https://github.com/Rhymen/go-whatsapp). I just wrote the wrapper for libpurple.
