### ISSUE TITLE
Display QR code in popup

### ISSUE THREAD

**Issue by EionRobb** [hoehermann/purple-gowhatsapp#30]
Using the purple_request* api, its possible to display an image in a popup, eg https://github.com/EionRobb/pidgin-opensteamworks/blob/master/steam-mobile/libsteam.c#L378-L412

Consider using it for the initial QR code display, to make it easier to scan from a phone?

**Comment by hoehermann** [comment]
Yes, I am considering it. Good idea. Thanks for the example code.

(Though I have to admit I did not see that – nowadays – clicking a link seems to be considered a hassle when on Windows.)

**Comment by hoehermann** [comment]
Added in 4f7f9da.
