### ISSUE TITLE
Debian 10: error during login

### ISSUE THREAD

**Issue by lxde70git** [hoehermann/purple-gowhatsapp#33]
I builded go-whatsapp from sources and when I connect with my account I received the following error: "error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}"
Same error using the prebuilt library which I found in https://buildbot.hehoe.de/purple-gowhatsapp/builds/current
I'm using Debian 10 LXDE 64bit, go version go1.13 linux/amd64, pidgin version 2.13.0

**Comment by hoehermann** [comment]
This looks very much like #15. It does not happen on my system. Neither with the current nightly nor with a fresh local built. I assume there is an old version of the plug-in involved on your system.

**Comment by pomarec** [comment]
duplicate of #40 aswell ?

**Comment by hoehermann** [comment]
Yes.
