### ISSUE TITLE
When not-inlining images, no link is shown

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/purple-gowhatsapp#34]

**Comment by nihilus** [comment]
So I see this is still valid, right? I can try fixing it.

**Comment by hoehermann** [comment]
> So I see this is still valid, right?

Actually, I am not sure. This is more a reminder "I should be looking into this".

**Comment by nihilus** [comment]
Looks like it to me, got friends sending images. I don't know why they prefer to do that and the messages are "missing in action" .

**Comment by hoehermann** [comment]
I just tried it. It works for me in both modes (link and embedded). ImageMessage is received, the image is downloaded, stored, message gets forwarded, and processed. Both link and caption are shown. So if it does not work for you, it would be even cooler if you would look into it as I cannot reproduce this issue myself. Keep in mind that the "Conversation Colors" plug-in eats images.

**Comment by nihilus** [comment]
@hoehermann Ah, might be that plugin that removes them.

**Comment by hoehermann** [comment]
Good to know that option has the intended effect. Maybe we should put in a message "contact sent an image, but download is disabled"?

**Comment by nihilus** [comment]
Yeah, instead of an empty message it would be good to know what happened.
