### ISSUE TITLE
text rendering for QR code (to support text only clients)

### ISSUE THREAD

**Issue by dm8tbr** [hoehermann/purple-gowhatsapp#35]
I spent some time trying to whack the pidgin config generated by pidgin into bitlbee-pidgin, but failed.
My problem is, that I get presented with this during login:
```
12:45:58 < login> dm8tbr: Scan this QR code within 20 seconds to log in.<img id="1">
12:46:18 <@root> hehoe-gowhatsapp - Login error: error during login: qr code scan timed out
12:46:18 <@root> hehoe-gowhatsapp - Logging in: Signing off..
```
I looked around but didn't see an option to dump the image reference to a file or something like that within bitlbee-purple, to possibly work around.

I'd give it a try myself, but I'm not familiar with go at all.
Any chance you could integrate something like https://github.com/fumiyas/qrc or https://github.com/mdp/qrterminal -- both of which seem to be go libraries for rendering QR codes to text / terminals.

**Comment by hoehermann** [comment]
There is an option for exactly this use-case. Unfortunately, I broke it (which is why #34 exists) with one of the recent modifications. Until I fix it, you could try one of the older versions found at https://buildbot.hehoe.de/purple-gowhatsapp/builds/. Version [0.0.4](https://buildbot.hehoe.de/purple-gowhatsapp/builds/libgowhatsapp_0.0.4~git6d997ae+gowhatsapp~gitd7754af_amd64_ubuntu18.04.so) could work for you. I do not know how to do it in bitlbee, but be sure to set the options "download-attachments" to 1 (true) and "inline-images" to 0 (false).

**Comment by hoehermann** [comment]
@dm8tbr Is https://buildbot.hehoe.de/purple-gowhatsapp/builds/libgowhatsapp_0.0.6~git2a0d182+gowhatsapp~git1a11f6d_amd64_ubuntu18.04.so doing anything for you?

**Comment by hoehermann** [comment]
As there are no responses, I assume this issue is now resolved.

**Comment by zer0def** [comment]
Can confirm that as of `2ba1c1a838e3bcce108015660e84e734789688a8`, setting `download-attachments` to `true` and `inline-images` to `false` drops a QR code image at a specified path and allows to log in.

**Comment by hoehermann** [comment]
I prepared a [branch](https://github.com/hoehermann/purple-gowhatsapp/tree/login_requests) which handles logins via libpurple requests API as proposed in #30. I am displaying both, the QR code as an image as well as the raw data which can be turned into a scan-able QR code with various [tools](https://www.the-qrcode-generator.com/). @zer0def Does this anything for you? I prepared a binary [here](https://ssl.hehoe.de/temp/libgowhatsapp_x86_64.so).

**Comment by zer0def** [comment]
Thanks for explicitly prepping a binary, though I am using https://aur.archlinux.org/packages/purple-gowhatsapp-git/ .

@hoehermann As `login_requests` branch currently stands, there's no message or request from Bitlbee to scan the code at all right now.

**Comment by hoehermann** [comment]
I added an option `plain-text-login` for explicitly requesting a plain text login. Links above have been updated. Please try again.

**Comment by zer0def** [comment]
Yup, `login_requests` as of `e8d8e78e9212a4b23626438d3721ff2354f9b5ce` displays the text payload and a `qrencode` render works just fine to establish a session.

**Comment by hoehermann** [comment]
Merged with master.

**Comment by Texou-** [comment]
Hi

Many thanks for this new feature, potentially great. My problem to use it is: how should I cut and paste, then pipe in qrencode, open the image, scan it, in 20 seconds? The longest thing is here cut and paste as the key does not go in one line. Could the feature add the get string in the clipboard automatically? Would help so much.

Thanks for this or any advice 

Best regards

**Comment by hoehermann** [comment]
I think I understand your problem, but I do not understand your suggestion. It sounds contradictory to me.

A text-only client like finch does not even have access to the clipboard because that is a GUI thing.  
Bridge services like spectrum and bitlbee cannot execute code on the final recipients' machines.

Maybe you can clarify by describing what kind of setup are you using that neither plain-text login nor embedded QR code works, but qrencode and a client-side GUI is available.

**Comment by Texou-** [comment]
Hi,

Oh yes, I was not clear enough. Here I use Bitlbee in a graphical 
terminal (for accessibility resaons of the IRC client + need of grapical 
tools). My initial idea was then: I run the auth process in the 
graphical terminal, the string is in the clipboard in parallel of being 
displayed, I cut and paste via shift-ctrl-v as an argument of qrencode, 
and display the png file to scan it.

I was advised, for a pure console usage, to pipe the string from the 
client to the commandline as an argument oqrencode, but I dont know how 
to script this as the iput is a text client. But would ork too.

Best regards

**Comment by hoehermann** [comment]
@Texou- Sorry, but automating login procedures is out of the scope of this protocol plug-in. If you need to pipe chat data into programs, use a separate plug-in. Something like

    # purple-gowhatsapp-login.pl
    # based on espeakeasy.pl
    use Purple;
    %PLUGIN_INFO = (
        perl_api_version => 2,
        name => "purple-gowhatsapp-login",
        version => "0.1",
        summary => "TODO",
        description => "TODO",
        author => "Hermann Höhne",
        url => "",
        load => "plugin_load",
        unload => "plugin_unload",
    );
    sub plugin_init {
        return %PLUGIN_INFO;
    }
    sub plugin_load {
        $plugin = shift;
        $convs_handle = Purple::Conversations::get_handle();
        # Connect the perl sub 'receiving_im_msg_cb' to the event 'receiving-im-msg'
        Purple::Signal::connect($convs_handle, "receiving-im-msg", $plugin, \&receiving_im_msg_cb, "yyy");
    }
    sub plugin_unload {
        my $plugin = shift;
    }
    sub receiving_im_msg_cb {
        my ($account, $who, $msg, $conv, $flags) = @_;

        if ($who == "login@s.whatsapp.net") {
            $msg =~ m/[0-9A-Za-z@\/+,=]+==/g;
            Purple::Debug::info("purple-gowhatsapp-login", "Have login data \"$&\".\n");
            system(("qrencode \"$&\" -o - | display - &"));
        }
    }

. This is as far as I go. I want to concentrate on improving the plug-in.

**Comment by diego-treitos** [comment]
For anybody that reaches this issue, desperately looking for a solution to scan the QR code within 20 seconds from a text client. If that text client happens to be `weechat` (using bitlbee), I have a small (and far from optimal) script that does the job.

It requires the program `qrencode` installed.

These are the steps to use it:

1. Install `qrencode` (`apt install qrencode`)

2. Place the script in `~/.weechat/python/waqr.py`

3. Go to the `&bitlbee` buffer in weechat and type `/script load waqr.py`

4. Enable the whatsapp account in bitlbee with `account <account_number> on`

5. A QR code rendered with UTF8 characters should appear in the buffer.

Here is the script


```
#  Project: waqr
#  Description: Read qr in raw and call qrencode to show it in weechat
#  Author: Diego Blanco
#  License: GPL3
#
#  0.1

import weechat as weechat
import subprocess

NAME="waqr"
VERSION="0.1"
LICENCE="GPL3"
AUTHOR="Diego Blanco"
DESCRIPTION="Scan qrcode raw data from go-whatsapp and prints the qrcode by calling qrencode"
HOMEPAGE="http://www.treitos.com/"
CONFIG= {}

def on_receive(data, signal, signal_data):
    # Fetch server, msg and buffer
    server = signal.split(",")[0]
    msg = weechat.info_get_hashtable("irc_message_parse", {"message": signal_data})
    buffer = weechat.info_get("irc_buffer", "%s,%s" % (server, msg["channel"]))

    # Check if we get the buffer in the right server and we have the QR data line
    if buffer and server == 'bitlbee' and 'Login data for WhatsApp account' in msg["text"]:
        b64_code=msg["text"].split()[-2][:-4]
        qrcode=subprocess.check_output(["qrencode", "-t", "utf8", b64_code])
        weechat.prnt( weechat.current_buffer(), qrcode)
    return weechat.WEECHAT_RC_OK


# Load the script
if __name__ == "__main__":
    # Register plugin
    weechat.register(NAME, AUTHOR, VERSION, LICENCE, DESCRIPTION, "", "UTF-8")

    # Notify about the plugin being loaded
    weechat.prnt( weechat.current_buffer(), 'Scanning for raw Go-WhatsApp QR codes...' )

    # Watch incoming message
    weechat.hook_signal("*,irc_in2_privmsg", "on_receive", "")
```

NOTE: This script works right now but it might need modifications for future versions of Go-Whatsapp, it is not a well coded and properly thought script. It just does the job for now :)

**Comment by Texou-** [comment]
Hi,

Many thanks for this work, excellent idea! I reply lately because I was 
so busy, but still frustrated with no having whatsapp in my bitlbee.

So I set to true plain-text-login and download-attachments; false for 
inline-images.

I use weechat 3.0

At account activation, I get:
SystemEror: <built-in function prnt> returned a result with an error set

An idea about what I should check?

Regards

**Comment by hoehermann** [comment]
That sounds like a bug, nothing an end-user can do something about. This weekend, I already spent my free time to work on [purple-signal](https://github.com/hoehermann/purple-signal/tree/attachments). It is going to be a while until I can look into this issue.

**Comment by diego-treitos** [comment]
@Texou- Be sure to have the python plugin installed (In Debian/Ubuntu `weechat-python` package).

Also be sure to have `qrencode` installed and that it is in your `PATH`. If it still shows an error it might be related to character encoding, as the solution requires unicode characters.

**Comment by echoesofastolenlife** [comment]
> Maybe you can help me understand by describing what kind of setup are you using that neither plain-text login nor embedded QR code works, but qrencode and a client-side GUI is available.

A solution for those who use bluestacks or another android emulator where a phone camera is not available to scan a qr code would certainly be ideal

**Comment by hoehermann** [comment]
@echoesofastolenlife Good idea, but the official WhatsApp client does only support authentication by scanning a QR code. There is no way around it and WhatsApp does not want one. That is why there are some efforts to add virtual cameras to some emulators or compatibility layers such as Anbox https://github.com/anbox/anbox/issues/727, but I do not know of any one being ready to use.

**Comment by hoehermann** [comment]
This has been implemented in the whatsmeow re-write.
