### ISSUE TITLE
"qr code scan timed out" error, but no QR code shown

### ISSUE THREAD

**Issue by rrthomas** [hoehermann/purple-gowhatsapp#36]
Using Pidgin 2.13.0 on Ubuntu 18.04, I installed the latest (2020-01-01) build of the plugin in `~/.purple/plugins`. When I restart Pidgin, I am able to create an account. (I notice that the account has no icon, is that normal?) The bottom of my Buddy List then shows "Connecting" and after a while it gives the error "error during login: qr code scan timed out". But no QR code ever popped up. I had a look in the window list (I am using GNOME), and could see no window there (so it had not for example popped up under other windows).

I can't find anything about this in the closed issues or the Wiki page (BTW, the link from README to "Common problems" seems to be broken).

**Comment by EionRobb** [comment]
Are you using the "Conversation Colors" plugin? If so, disable it

**Comment by rrthomas** [comment]
Thanks for responding! No, I'm not using the "Conversation Colors" plugin.

**Comment by hoehermann** [comment]
This seems to be a variant of #35 and #34. Long story short: I broke the image display. I want to fix it, but I cannot make the time right now.

**Comment by rrthomas** [comment]
Thanks for the explanation. I've subscribed to #34.

**Comment by hoehermann** [comment]
@rrthomas Is https://buildbot.hehoe.de/purple-gowhatsapp/builds/libgowhatsapp_0.0.6~git2a0d182+gowhatsapp~git1a11f6d_amd64_ubuntu18.04.so doing anything for you?

**Comment by rrthomas** [comment]
Thanks for the suggestion! No change, it behaves exactly as before.

**Comment by hoehermann** [comment]
@rrthomas Dang. Can you show `pidgin -d | grep whats`?

**Comment by rrthomas** [comment]
Sure:

    $ pidgin -d |grep whats
    (19:49:26) plugins: probing /home/rrt/.purple/plugins/libgowhatsapp_0.0.6~git2a0d182+gowhatsapp~git1a11f6d_amd64_ubuntu18.04.so
    (19:49:26) account: Connecting to account 447791179665@s.whatsapp.net.
    (19:49:27) gowhatsapp: Recieved message at 0 id  remote login@s.whatsapp.net sender  (fromMe 0, system 1): Scan this QR code within 20 seconds to log in.
    (19:49:27) log: Failed to open log file "/home/rrt/.purple/logs/login@s.whatsapp.net.log" for reading: No such file or directory
    (Pidgin:3203): Json-CRITICAL **: 19:49:27.408: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed
    (19:49:47) gowhatsapp: Recieved message at 0 id (null) remote (null) sender (null) (fromMe 0, system 0): error during login: qr code scan timed out
    (19:49:47) account: Disconnecting account 447791179665@s.whatsapp.net (0x55aeeb430500)

I filtered out all the messages about missing icons.

**Comment by hoehermann** [comment]
The message "Scan this QR code within 20 seconds to log in." is mentioned in the debug output. That is good. But is is displayed in the GUI?  
Try toggling "display images in the conversation" in the plug-in's advanced options. Does anything change?

**Comment by rrthomas** [comment]
As reported originally, no QR code is displayed. No window is opened in which it could be displayed.

**Comment by EionRobb** [comment]
Check in Tools->Privacy to see if the `login@s.whatsapp.net` user is blocked.  Or do you have any plugins that would block new IM's for people who aren't on your buddy list?

**Comment by rrthomas** [comment]
I looked in Tools→Privacy, and the WhatsApp account has "Allow all users to contact me". (I have to check this quite quickly, because once the QR code period has expired, the WhatsApp account disappears from the "Set privacy for" dropdown list.)

I am not sure what you mean about that particular user being blocked; where would that be set?

I had a look at my list of plugins enabled, and I can't see anything relevant.

**Comment by hoehermann** [comment]
@rrthomas 
> No window is opened in which it could be displayed.
This is the actual problem. A normal conversation window should pop up and show the QR code. Please try to log in while "display images in conversation window after download" is not selected. There should be a file at `~/.purple/gowhatsapp/login`. It contains the QR code. Open it in your favourite image viewer or your browser or `display` and scan it. With any luck, normal messages will come through afterwards. Keep an eye on the debug output to see whether anything is happening.

**Comment by rrthomas** [comment]
OK, that seems to have worked. I opened the image and scanned it during the 20-second window. Then about 100 windows opened with messages from conversations spanning several months!

No contacts, nor even a WhatsApp heading, but I can't tell whether that's normal at the moment or not.

Thanks very much for your help getting this far. I guess this issue is still a problem, though, in that the barcode is not displayed as it should be; maybe worth documenting the workaround?

**Comment by hoehermann** [comment]
> about 100 windows opened with messages from conversations spanning several months

This is intentional. It is the entire history as delivered by the WhatsApp services.

> No contacts, nor even a WhatsApp heading

Contacts are not automatically added to the buddy-list. You can do so manually via the menu (either the buddy-list's or the conversation window's).

> Thanks very much for your help getting this far.

You are welcome.

> worth documenting the workaround?

Probably. Moreover, I'd like to find out what causes this behaviour and fix the underlying problem. There is not much I can do as long as I cannot reproduce it.

> the link from README to "Common problems" seems to be broken

Indeed, I want to fix that right away.

**Comment by hoehermann** [comment]
As of 4f7f9da, this should no longer impose a problem.
