### ISSUE TITLE
New lines are being sent as new messages

### ISSUE THREAD

**Issue by johnwuelk** [hoehermann/purple-gowhatsapp#37]
Every new line is being separated as a new message, although it should be in one message.
I hope this is something easy to fix.
And is there any chance to use it while the phone is offline?

**Comment by hoehermann** [comment]
I know of this issue (see the the [README](https://github.com/hoehermann/purple-gowhatsapp#what-could-be-done-next)). It is probably easy, but it is also boring. Pull requests are welcome.

As this plug-in uses WhatsApp Web, the phone must be online. If you want a solution without the official client being involved, there is [yowsup](https://github.com/tgalal/yowsup). WhatsApp bans custom clients, though.

**Comment by johnwuelk** [comment]
Thanks for the prompt response. I rather use your plugin, it's safer.
