### ISSUE TITLE
Messages are sent with HTML entities

### ISSUE THREAD

**Issue by ae-bogdan** [hoehermann/purple-gowhatsapp#4]
![image](https://user-images.githubusercontent.com/17846988/54632664-49296200-4a87-11e9-8941-7a999a03ab3a.png)

`&gt;` should obviously have been `>`

**Comment by hoehermann** [comment]
Confirmed. Though I do not know where this is coming from. I specifically did not enable `PURPLE_CONNECTION_HTML`. I keep this as a note for later.
