### ISSUE TITLE
Suddenly stopped login

### ISSUE THREAD

**Issue by b2cbd** [hoehermann/purple-gowhatsapp#40]
`error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}`

I tried reset/relogin. It doesn't work anymore.

**Comment by EionRobb** [comment]
https://github.com/Rhymen/go-whatsapp/issues/305

**Comment by b2cbd** [comment]
@EionRobb  Thanks! Is there any upgraded compiled dll available for windows?

**Comment by hoehermann** [comment]
Yes, EionRobb suppiled a new dll: https://github.com/hoehermann/purple-gowhatsapp/wiki/Windows-Build
