### ISSUE TITLE
Cannot compile in 32bit-Ubuntu

### ISSUE THREAD

**Issue by Howy-1** [hoehermann/purple-gowhatsapp#41]
I want to compile purple-gowhatsapp, but I have many errors like this:

    purplegwa.a(000000.o):(.data.rel.local+0x4): multiple definition of `GOWHATSAPP_FAKE_ONLINE_OPTION'
    /tmp/ccxNumtC.o:(.data.rel.local+0x9c): first defined here

    purplegwa.a(000000.o): In function `gowhatsapp_go_sendMessage':
    /tmp/go-build/command-line-arguments/_obj/_cgo_export.c:27: multiple definition of `GOWHATSAPP_SESSION_CLIENDID_KEY'
    /tmp/ccxNumtC.o:/home/dirk/purple-gowhatsapp/libgowhatsapp.c:290: first defined here

    /tmp/go-build/command-line-arguments/_obj/_cgo_export.c:26: multiple definition of `GOWHATSAPP_DOWNLOAD_TRY_ONLY_ONCE_OPTION'
    /tmp/ccxNumtC.o:/home/dirk/purple-gowhatsapp/libgowhatsapp.c:287: first defined here

    purplegwa.a(000000.o): In function `gowhatsapp_go_sendMessage':
    /tmp/go-build/command-line-arguments/_obj/_cgo_export.c:18: multiple definition of `GOWHATSAPP_RESTORE_SESSION_OPTION'
    /tmp/ccxNumtC.o:/home/dirk/purple-gowhatsapp/libgowhatsapp.c:292: first defined here

    collect2: error: ld returned 1 exit status
    Makefile:55: die Regel für Ziel „libgowhatsapp.so“ scheiterte
    make: *** [libgowhatsapp.so] Fehler 1

The lines with "first defined here" are many more...

Regards, Dirk

**Comment by hoehermann** [comment]
This happens if the constants declared in `constants.h` are defined by compilation more than once. Are you using the supplied makefile? Is go successful in setting the [CFLAGS](https://github.com/hoehermann/purple-gowhatsapp/blob/2ba1c1a838e3bcce108015660e84e734789688a8/purplegwa.go#L67)? Does the [ifdef](https://github.com/hoehermann/purple-gowhatsapp/blob/2ba1c1a838e3bcce108015660e84e734789688a8/constants.h#L6) pick it up in your set-up?

**Comment by Howy-1** [comment]
I have used all original files, also the makefile. 
Now i have tested it on an other system, and the compiling was successful. But pidgin crashes when the whatsapp-account is activated.

**Comment by hoehermann** [comment]
Please close Pidgin, run `gdb pidgin` in a console, enter `run`, trigger the crash in the newly started Pidgin, then enter `bt` into gdb, paste the backtrace here.

**Comment by hoehermann** [comment]
ca7f536 contains some 32 bit related fixes. Please try again.

**Comment by hoehermann** [comment]
Closing due to lack of response.
