### ISSUE TITLE
Mark new messages as read only when the conversation window has been displayed

### ISSUE THREAD

**Issue by Nardol** [hoehermann/purple-gowhatsapp#47]
When a message is received, the notification on phone is not displayed because the message is marked as read, even if the concerned conversation window has not been displayed.
If we are nearer the phone, we cannot reply to the message directly using the notification icon.

Would it be possible to mark messages as read only when the conversation window has been displayed instead of marking it as read directly?

**Comment by hoehermann** [comment]
I do not know whether it is possible at all. As far as I know, libpurple does not offer a mechanism for this. Messages are received, processed and displayed immediately. I could add a global option "do not mark messages as read" option. Would this be of any help for you?

**Comment by Nardol** [comment]
The plugin https://github.com/EionRobb/skype4pidgin do it. When I open the conversation windows, the notification is not displayed anymore on my phone.
On IRC, when I receive a message, the notification icon change when I open the conversation window where there are some unread message so I think it is possible.

About the compromise you talk, I have not any better idea ;) so why not after all if it is really not possible.

**Comment by nihilus** [comment]
Well, you should afaik get a JSON callback and parse the data out and handle it. gowhatsapp has from what I've been dugging into during the night lots of magic, the RAWMessagehandler as such might be one way if everything else fails.

Recall you cannot compare skype and whatsapp on the protocol / functionality level; exemplia gratia: Skype has a on signed-on/signed-off notification which is not even part of the whatsapp client on the phone.

**Comment by hoehermann** [comment]
@Nardol You are right. There seems to be some kind of signal "conversation-updated" used [here](https://github.com/EionRobb/skype4pidgin/blob/a1f31838fd317a49eb1f23fd078d57f05a919da2/skypeweb/libskypeweb.c#L360). I did not know that existed. Thank you for pointing that out. It works per conversatio, though. The whatsapp plug-in would need to store a map of all unread message IDs so [Read](https://github.com/hoehermann/purple-gowhatsapp/blob/7d75b46e403f774b4ef62a9b833dfc177c19c919/purplegwa.go#L186) can be invoked when the signal is fired. Definitely doable. I'll mark this as a requested enhancement. Contributions are welcome.

**Comment by Grarie** [comment]
@hoehermann As you suggested it, could you add the global option "do not mark messages as read" option? Or could you tell, how one can do it on his own without having to understand most of the source code?  This would definitely help me. :)

**Comment by hoehermann** [comment]
If you compile yourself, you can remove [the call to Read](https://github.com/hoehermann/purple-gowhatsapp/blob/be9ccd134ced6cbe863a72e212311d605d359f01/purplegwa.go#L191). I am quite booked currently, but I might add a user-configurable preference option in October.

**Comment by hoehermann** [comment]
@Grarie A user-configurable option has been added in 85223aa.

**Comment by Grarie** [comment]
Thank you very much. The former solution worked as well but now I don't have to manually fiddle in code every time I compile. Very nice! :)

**Comment by hoehermann** [comment]
The whatsmeow branch now includes a "send receipt on answer" setting. I have not figured out how to use the `conversation-updated` signal correctly.
