### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by b2cbd** [hoehermann/purple-gowhatsapp#50]
Suddenly it stops! I tried to re-login, it doesn't work. I'm using the [windows build](https://github.com/EionRobb/purple-gowhatsapp/issues/4#issuecomment-610829146) from @EionRobb . Other protocols work fine.

> error during login: login connection timed out

```
(08:51:30) gowhatsapp: 3773XXX recieved message type -1 at 0 id (null) remote (null) sender (null) (fromMe 0, system 0): error during login: login connection timed out
(08:51:30) connection: Connection error on 3773XXX (reason: 16 description: error during login: login connection timed out)
(08:51:30) jabber: jabber_actions: have pep: NO
(08:51:30) gowhatsapp: 3773XXX recieved message type -1 at 0 id (null) remote (null) sender (null) (fromMe 0, system 0): keepAlive failed: connection timed out
(08:51:30) gowhatsapp: 3773XXX recieved message type -1 at 0 id (null) remote (null) sender (null) (fromMe 0, system 0): server closed connection,code: 1000,text: 
(08:51:30) account: Disconnecting account XXX (XXX)
(08:51:30) connection: Disconnecting connection 3773XXX
(08:51:30) jabber: jabber_actions: have pep: NO
(08:51:30) connection: Destroying connection 3773XXX
```

**Comment by hoehermann** [comment]
Have you tried bringing WhatsApp to the front (on your phone)?

**Comment by EionRobb** [comment]
Windows build from this change 
[libgowhatsapp.zip](https://github.com/hoehermann/purple-gowhatsapp/files/4514829/libgowhatsapp.zip)

**Comment by hoehermann** [comment]
Just a hint to all who come here via google: Updated binaries are available [here](https://buildbot.hehoe.de/purple-whatsmeow/builds/).
