### ISSUE TITLE
Order of pervious message is as received and not by timestamp

### ISSUE THREAD

**Issue by nihilus** [hoehermann/purple-gowhatsapp#51]
As one can easily see the order is not in order (pun intended):
```
(2020-05-02 14:53:31) XXX: läser mkt samtidigt, så jag vet vad ska jag skriva
(2020-05-02 16:17:48) XXX: Fan vad jag vill röka
(2020-05-02 14:53:13) Markus: Tur att du har hela helgen på dig
(2020-05-02 14:53:36) Markus: Mmm
```

**Comment by nihilus** [comment]
Also me latest message from the phone-app is not showed.

**Comment by nihilus** [comment]
@EionRobb flags |= PURPLE_MESSAGE_SEND | PURPLE_MESSAGE_REMOTE_SEND | PURPLE_MESSAGE_DELAYED;
Why does it have to be marked as 'delayed'?

**Comment by nihilus** [comment]
Seems related to issue #32

**Comment by hoehermann** [comment]
I know. After connecting, the server sends a burst of messages in random order. I'd need to collect them, sort them, and then display them. Problem is: I do not know when the burst is over. It seems to depend on internet connectivity, service quality, size of attachments, and the current phase of the moon. I described the problem in another issue, but I cannot find my original comment right now. I have no idea how to really solve this problem. It does not bother me enough to implement a half-good fix.

**Comment by EionRobb** [comment]
> @EionRobb flags |= PURPLE_MESSAGE_SEND | PURPLE_MESSAGE_REMOTE_SEND | PURPLE_MESSAGE_DELAYED;
> Why does it have to be marked as 'delayed'?

"send" is for pidgin, "remote send" is for bitlbee and spectrum2, "delayed" is for Adium

**Comment by hoehermann** [comment]
This does not happen with the whatsmeow branch.
