### ISSUE TITLE
Opens a lot of conversation windows and crashes pidgin

### ISSUE THREAD

**Issue by jerinphilip** [hoehermann/purple-gowhatsapp#53]
Builds I have used in the past downloads all past messages and opens a chat window, sometimes crashing the entire pidgin application. Is this a known issue?

I run pidgin 2.x.x on Windows and use a recent dll.

**Comment by hoehermann** [comment]
Maybe. Something seems to be awry, especially with downloads. But only some times, which makes debugging hard. See #52. Without the debug output, I can only guess.

You can also check the options. Maybe one of them helps you:

* The "Do not show messages older than previous session" option added in added in 29ebaa6.
* Disable "Download files from media messages".
* Increase "Number of received messages to remember as already shown".

**Comment by hoehermann** [comment]
Closing unresolved due to inactivity.
