### ISSUE TITLE
make fails from many redefinitions

### ISSUE THREAD

**Issue by dchmelik** [hoehermann/purple-gowhatsapp#57]
Make fails because of ld leading to many things being redefined earlier: 
[purple-gowhatsapp make error log](https://gist.github.com/dchmelik/2eb1e722cae7f70bf1224ebcf5ef26ce).

**Comment by hoehermann** [comment]
I do not even fully understand the error. An example with paths and names stripped:

    gwa-to-purple.o: constants.h:44: multiple definition of SYMBOL; gwa-to-purple.o: constants.h:44: first defined here

Dear linker, yes, `SYMBOL` was defined in that line. Though it mentions the same line twice. I cannot really tell what is supposed to be wrong there. Is it possible your version of cgo (in the golang compiler) does not pick up `CFLAGS: -DCGO` in `purplegwa.go`? 

Also, it looks like you are building with MSYS. In case you missed it, please notice I now also provide [builds for win32](https://buildbot.hehoe.de/purple-gowhatsapp/builds/).

**Comment by dchmelik** [comment]
I have gcc-9.3.0-x86_64-2... no idea what cgo it has.  Haven't used Windows for a PC in over 10 or 15 years...

**Comment by hoehermann** [comment]
So which distribution are you using?

**Comment by dchmelik** [comment]
> So which distribution are you using?

Slackware GNU/Linux; later probably also *BSD Unix.

**Comment by hoehermann** [comment]
I just fiddled around with Slackware for an hour and came to the conclusion investigating this is not worth my time. Maybe I have grown to fond of the ease-of-use of Debian-based systems, but I won't spend hours of compiling basic stuff myself just to have a graphical UI. Sorry, you are on your own with this one.

**Comment by dchmelik** [comment]
The Debian way is no automatic graphical user interface (GUI,) but you have to get more advanced ones separately.  On Slackware, they're already there.  Simply choose one during installation (or as root run /var/log/setup/setup.xwmconfig ) then startx.

**Comment by hoehermann** [comment]
That is precisely what I did. Yet `startx` fails since it cannot load `libnettle.so.6`. It looks like I need to know of, collect and install all dependencies manually. I do not want to do so – that is what a package manager should be for. 

Allegedly, the Slackware "huge" kernel is compiled without noveau and does not support my Intel graphics adapter, either. I have no idea, why the fallback to vesa or fbdev is not an option. Apart from that, the Slackware kernel panics in qemu, so I need to use a physical install. 

At that point, I gave up. I do not see any point in me trying to familiarize myself with a distribution I probably won't be using afterwards just to investigate a problem which you already can track down on your machine as you have everything setup. It is not like I know anything about Slackware, golang or the cgo mechanics more than you do.

**Comment by dchmelik** [comment]
Wow; never seen such bad crashes from Slackware (at least in 10+ years)... probably one shouldn't use Slackware-current (rather than stable 14.2 but updated) unless testing (I'm testing.)  If it'd compile on 14.2, it'll probably compile on current... but some 14.2 packages are getting old (gcc 4)... so wouldn't necessarily try... I don't even use WhatsApp yet;  someone I know does, so I thought I'd try.  I'll give this another try as soon as one of my OSes has a stable release or seems they update anything related (libraries, golang, though I don't know much about it yet.)  Thanks for going to extra lengths to see if it'd work!

**Comment by hoehermann** [comment]
Thank you for your considerations. I guess the Intel graphics would probably work if I installed the appropriate binary blob of firmware (I know that procedure from Debian; Ubuntu includes it by default). And the kernel panic in qemu is really weird. It is probably a simple qemu setting 
or Slackware kernel parameter or idontknowwhat I need to adjust.

It is a unfortunate combination of a series of little issues, I presume. Each on therir own can be easily solved with a little of digging, but I'd rather want to focus on the plug-in itself than compilation issues on this specific platform.

**Comment by hoehermann** [comment]
@dchmelik As mysteries of not working software entice me more than they should, I gave Slackware another shot today. It looks like I tried to boot the "general" kernel, which is too bare bones to successfully run on my system. I was moderately successful with the "huge" kernel: It boots and I can use the system. However, `gcc-go` won't compile the purple-gowhatsapp sources at all and https://slackbuilds.org/repository/14.2/development/google-go-lang/ fails as go is not installed. I do not really want to investigate any further, but it seems cannot promise I won't. :|

**Comment by dchmelik** [comment]
No worries... if enticed again, you could try prebuilt [SlackOnly: google-go-lant](http://slackonly.com/pub/packages/14.2-x86_64/development/google-go-lang).  Years ago people didn't know much about SlackOnly (a Greek guy, made it, then appeared in the English-speaking forums)... I used SlackOnly packages for years.

Anyway, after Slackware-current added pluggable authentication modules (PAM,) I've been reinstalling (dislike PAM defaults) so now have to recompile BitlBee, and dozens of plugins for it and Pidgin... mostly others before WhatsApp... might be some days/weeks getting through all that...

**Comment by dchmelik** [comment]
I've now built a libpurple whatsapp that was listed in sbopkg... but when I went to pidgin.im and bitlbee.org, I thought they linked to this repository of yours here... the one in sbopkg doesn't... so I'm not sure which is used more.  If yours is the more common one I'll still try building it later...
