### ISSUE TITLE
Can't connect using HTTP/Socks5 proxy

### ISSUE THREAD

**Issue by karimmd** [hoehermann/purple-gowhatsapp#58]
Is there any way to connect whatsapp through socks5 or http proxy similar to Hangouts or Skype in Pidgin.

While trying the similar way, I was getting this error:
couldn't dial whatsapp web websocket: dial tcp 31.13.72.34:443: i/o timeout

**Comment by hoehermann** [comment]
Using a proxy is currently not supported at all. Adding [proxy support](https://github.com/Rhymen/go-whatsapp/blob/master/examples/loginWithProxy/main.go) seems is fairly simple. I actually is on the whish-list of features mentioned in the [README](https://github.com/hoehermann/purple-gowhatsapp/blob/master/README.md).

**Comment by hoehermann** [comment]
I want to keep this issue open so I do not forget about the request.

**Comment by hoehermann** [comment]
Feel free to test the current nightly version 0.2.0~git99826b8. I just tried a SOCKS 5 proxy and it seemed to work okay. You need to enter the proxy settings directly into the account's "proxy" tab. It does not pick up Pidgin's global proxy settings or proxy settings defined via environment variable.

**Comment by karimmd** [comment]
Thanks for the effort. I will test and will let you know. Keep up your excellent work.

**Comment by karimmd** [comment]
It does works while my phone is running on the top of the Proxy server. That means messages written from pidgin WhatsApp client is still required to wait for the validation from the WhatsApp main app running on the phone. Maybe that's how they designed WhatsApp.

**Comment by hoehermann** [comment]
Yes, that is indeed how it is designed. There are other projects like yowsup which emulate a direct connection without the need of a phone running the official app. WhatsApp goes great lengths to identify and ban these "rogue" clients. :( Glad to hear it works for you within the given restrictions.
