### ISSUE TITLE
Finch not displaying qrcode

### ISSUE THREAD

**Issue by gsadovski** [hoehermann/purple-gowhatsapp#59]
# Problem

Dear all,

`Finch` is failing to display the QR code necessary to logon as can be shown in the image below:

![2020-06-01-133858_792x424_scrot](https://user-images.githubusercontent.com/36942300/83376708-4148aa00-a40e-11ea-900d-46cc3ea854d7.png)

# Warnings
I'm not fully sure about the origin of the problem, though the building of `purple-gowhatsapp` did display some warnings. The output of `$sudo make clean install` was:

	> rm -f libgowhatsapp.so purplegwa.a gwa-to-purple.o
	> cc -O2 -g -ggdb -pipe -Wall -std=c99 -DGOWHATSAPP_PLUGIN_VERSION='"0.2.0~gite1bdd1f"' -DMARKDOWN_PIDGIN -DLOCALEDIR=\"/usr/share/locale\" -c -o gwa-to-purple.o gwa-to-purple.c
	> go get github.com/skip2/go-qrcode
	> go get github.com/gabriel-vasile/mimetype
	> go build -buildmode=c-archive -o purplegwa.a purplegwa.go purplegwa-media.go
	> cc -O2 -g -ggdb -pipe -Wall -std=c99 -DGOWHATSAPP_PLUGIN_VERSION='"0.2.0~gite1bdd1f"' -DMARKDOWN_PIDGIN -DLOCALEDIR=\"/usr/share/locale\" -fPIC -shared -o libgowhatsapp.so libgowhatsapp.c purplegwa.a purple2compat/http.c purple2compat/purple-socket.c -Wl,-z,relro `pkg-config purple glib-2.0 --libs --cflags`  -Ipurple2compat
	> In file included from /usr/include/libpurple/media/codec.h:35,
	>                  from /usr/include/libpurple/media.h:31,
	>                  from /usr/include/libpurple/prpl.h:75,
	>                  from /usr/include/libpurple/buddyicon.h:39,
	>                  from /usr/include/libpurple/blist.h:110,
	>                  from /usr/include/libpurple/status.h:133,
	>                  from /usr/include/libpurple/connection.h:151,
	>                  from /usr/include/libpurple/account.h:49,
	>                  from /usr/include/libpurple/purple.h:48,
	>                  from purple_compat.h:19,
	>                  from libgowhatsapp.c:41:
	> /usr/include/libpurple/media/../util.h:1397:13: warning: Deprecated pre-processor symbol, replace with 
	>  1397 | G_CONST_RETURN gchar *purple_gai_strerror(gint errnum);
	>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
	> In file included from /usr/include/libpurple/prpl.h:75,
	>                  from /usr/include/libpurple/buddyicon.h:39,
	>                  from /usr/include/libpurple/blist.h:110,
	>                  from /usr/include/libpurple/status.h:133,
	>                  from /usr/include/libpurple/connection.h:151,
	>                  from /usr/include/libpurple/account.h:49,
	>                  from /usr/include/libpurple/purple.h:48,
	>                  from purple_compat.h:19,
	>                  from libgowhatsapp.c:41:
	> /usr/include/libpurple/media.h:165:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   165 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/purple.h:48,
	>                  from purple_compat.h:19,
	>                  from libgowhatsapp.c:41:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> In file included from /usr/include/libpurple/prpl.h:75,
	>                  from /usr/include/libpurple/buddyicon.h:39,
	>                  from /usr/include/libpurple/blist.h:110,
	>                  from /usr/include/libpurple/status.h:133,
	>                  from /usr/include/libpurple/connection.h:151,
	>                  from /usr/include/libpurple/account.h:49,
	>                  from /usr/include/libpurple/purple.h:48,
	>                  from purple_compat.h:19,
	>                  from libgowhatsapp.c:41:
	> /usr/include/libpurple/media.h:214:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   214 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/purple.h:48,
	>                  from purple_compat.h:19,
	>                  from libgowhatsapp.c:41:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> In file included from /usr/include/libpurple/media/codec.h:35,
	>                  from /usr/include/libpurple/media.h:31,
	>                  from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/http.h:33,
	>                  from purple2compat/http.c:22:
	> /usr/include/libpurple/media/../util.h:1397:13: warning: Deprecated pre-processor symbol, replace with 
	>  1397 | G_CONST_RETURN gchar *purple_gai_strerror(gint errnum);
	>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
	> In file included from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/http.h:33,
	>                  from purple2compat/http.c:22:
	> /usr/include/libpurple/media.h:165:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   165 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/http.h:33,
	>                  from purple2compat/http.c:22:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> In file included from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/http.h:33,
	>                  from purple2compat/http.c:22:
	> /usr/include/libpurple/media.h:214:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   214 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/http.h:33,
	>                  from purple2compat/http.c:22:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> In file included from /usr/include/libpurple/media/codec.h:35,
	>                  from /usr/include/libpurple/media.h:31,
	>                  from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/purple-socket.h:31,
	>                  from purple2compat/purple-socket.c:22:
	> /usr/include/libpurple/media/../util.h:1397:13: warning: Deprecated pre-processor symbol, replace with 
	>  1397 | G_CONST_RETURN gchar *purple_gai_strerror(gint errnum);
	>       |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
	> In file included from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/purple-socket.h:31,
	>                  from purple2compat/purple-socket.c:22:
	> /usr/include/libpurple/media.h:165:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   165 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/purple-socket.h:31,
	>                  from purple2compat/purple-socket.c:22:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> In file included from /usr/include/libpurple/blist.h:111,
	>                  from /usr/include/libpurple/buddyicon.h:37,
	>                  from /usr/include/libpurple/conversation.h:151,
	>                  from /usr/include/libpurple/log.h:53,
	>                  from /usr/include/libpurple/account.h:50,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/purple-socket.h:31,
	>                  from purple2compat/purple-socket.c:22:
	> /usr/include/libpurple/media.h:214:3: warning: ‘GParameter’ is deprecated [-Wdeprecated-declarations]
	>   214 |   guint num_params, GParameter *params);
	>       |   ^~~~~
	> In file included from /usr/include/glib-2.0/gobject/gobject.h:26,
	>                  from /usr/include/glib-2.0/gobject/gbinding.h:29,
	>                  from /usr/include/glib-2.0/glib-object.h:22,
	>                  from /usr/include/libpurple/account.h:31,
	>                  from /usr/include/libpurple/connection.h:149,
	>                  from purple2compat/purple-socket.h:31,
	>                  from purple2compat/purple-socket.c:22:
	> /usr/include/glib-2.0/gobject/gparam.h:271:8: note: declared here
	>   271 | struct _GParameter /* auxiliary structure for _setv() variants */
	>       |        ^~~~~~~~~~~
	> mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16
	> mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22
	> mkdir -m 0755 -p `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48
	> install -m 0644 -p icons/16/whatsapp.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/16/whatsapp.png
	> install -m 0644 -p icons/22/whatsapp.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/22/whatsapp.png
	> install -m 0644 -p icons/48/whatsapp.png `pkg-config --variable=datadir purple`/pixmaps/pidgin/protocols/48/whatsapp.png
	> mkdir -m 0755 -p `pkg-config --variable=plugindir purple`
	> install -m 0755 -p libgowhatsapp.so `pkg-config --variable=plugindir purple`

# Setup

* Finch: v2.13.0 (f07927902113041d6fa291293d9205ea4f05e9e6)
* Terminal: st 0.8.3
* OS: Arch Linux x86_64
* Kernel: 5.6.14-arch1-1

**Comment by gsadovski** [comment]
Can confirm that with the following configs:

![2020-06-01-153758_1307x545_scrot](https://user-images.githubusercontent.com/36942300/83382360-e454f000-a41d-11ea-897b-9f75f0d9cb42.png)

A `.png` image is generated at `~/.purple/logs/...` containing the QR code. Accordingly to the Whatsapp app in my phone, logon has been successful though `finch` is crashing immediately after outputing the error:

       Segmentation fault (core dumped)

**Comment by gsadovski** [comment]
Finally, enabling `Do not show messages older than previous session` and increasing `Number of received messages to remember as already shown` to around 10000 allowed me to successfully logon.

![2020-06-01-163717_1926x542_scrot](https://user-images.githubusercontent.com/36942300/83386518-2b46e380-a426-11ea-8098-5b671939c852.png)

**Comment by hoehermann** [comment]
Thank you for your report. I am glad you figured out despite the problems. I should mention these in the list of [known problems](https://github.com/hoehermann/purple-gowhatsapp/wiki/Common-Problems).

The deprecation warnings are #42.  
The segfault after logon is eluding me in #53 and #52. I know of this problem, but it happened for me (even with a clean profile) only three times and never while debugging. It seems it only happens with bursts of messages.

**Comment by leolca** [comment]
Using the  nightly build versions I get ```Segmentation fault (core dumped)``` after scanning the QR.

I also tried to compile the source, but it went wrong and I could not find the config as mentioned above by @gsadovski .


```
$ make
go get github.com/Rhymen/go-whatsapp
cc -O2 -g -ggdb -pipe -Wall -std=c99 -DGOWHATSAPP_PLUGIN_VERSION='"0.2.0~git99826b8"' -DMARKDOWN_PIDGIN -DLOCALEDIR=\"/usr/share/locale\" -c -o gwa-to-purple.o gwa-to-purple.c
go get github.com/skip2/go-qrcode
go get github.com/gabriel-vasile/mimetype
go build -buildmode=c-archive -o purplegwa.a purplegwa.go purplegwa-media.go
# command-line-arguments
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_process_message_bridge':
/tmp/purple-gowhatsapp/gwa-to-purple.c:12: multiple definition of `gowhatsapp_process_message_bridge'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:12: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_get_account':
/tmp/purple-gowhatsapp/gwa-to-purple.c:18: multiple definition of `gowhatsapp_get_account'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:18: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_string':
/tmp/purple-gowhatsapp/gwa-to-purple.c:25: multiple definition of `gowhatsapp_account_get_string'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:25: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_bool':
/tmp/purple-gowhatsapp/gwa-to-purple.c:34: multiple definition of `gowhatsapp_account_get_bool'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:34: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_proxy':
/tmp/purple-gowhatsapp/gwa-to-purple.c:41: multiple definition of `gowhatsapp_account_get_proxy'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:41: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:44: multiple definition of `GOWHATSAPP_SESSION_WID_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:44: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:43: multiple definition of `GOWHATSAPP_SESSION_MACKEY_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:43: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:42: multiple definition of `GOWHATSAPP_SESSION_ENCKEY_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:42: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:41: multiple definition of `GOWHATSAPP_SESSION_SERVERTOKEN_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:41: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:40: multiple definition of `GOWHATSAPP_SESSION_CLIENTTOKEN_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:40: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:39: multiple definition of `GOWHATSAPP_SESSION_CLIENDID_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:39: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:34: multiple definition of `GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:34: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:29: multiple definition of `GOWHATSAPP_INLINE_IMAGES_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:29: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:28: multiple definition of `GOWHATSAPP_DOWNLOAD_TRY_ONLY_ONCE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:28: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:27: multiple definition of `GOWHATSAPP_DOWNLOAD_ATTACHMENTS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:27: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:26: multiple definition of `GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:26: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:25: multiple definition of `GOWHATSAPP_TIMESTAMP_FILTERING_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:25: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:24: multiple definition of `GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:24: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:23: multiple definition of `GOWHATSAPP_FAKE_ONLINE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:23: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:22: multiple definition of `GOWHATSAPP_PLAIN_TEXT_LOGIN'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:22: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:21: multiple definition of `GOWHATSAPP_GET_ICONS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:21: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:20: multiple definition of `GOWHATSAPP_FETCH_CONTACTS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:20: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:19: multiple definition of `GOWHATSAPP_RESTORE_SESSION_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:19: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_process_message_bridge':
/tmp/purple-gowhatsapp/gwa-to-purple.c:12: multiple definition of `gowhatsapp_process_message_bridge'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:12: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_get_account':
/tmp/purple-gowhatsapp/gwa-to-purple.c:18: multiple definition of `gowhatsapp_get_account'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:18: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_string':
/tmp/purple-gowhatsapp/gwa-to-purple.c:25: multiple definition of `gowhatsapp_account_get_string'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:25: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_bool':
/tmp/purple-gowhatsapp/gwa-to-purple.c:34: multiple definition of `gowhatsapp_account_get_bool'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:34: first defined here
/usr/bin/ld: gwa-to-purple.o: in function `gowhatsapp_account_get_proxy':
/tmp/purple-gowhatsapp/gwa-to-purple.c:41: multiple definition of `gowhatsapp_account_get_proxy'; gwa-to-purple.o:/tmp/purple-gowhatsapp/gwa-to-purple.c:41: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:44: multiple definition of `GOWHATSAPP_SESSION_WID_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:44: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:43: multiple definition of `GOWHATSAPP_SESSION_MACKEY_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:43: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:42: multiple definition of `GOWHATSAPP_SESSION_ENCKEY_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:42: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:41: multiple definition of `GOWHATSAPP_SESSION_SERVERTOKEN_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:41: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:40: multiple definition of `GOWHATSAPP_SESSION_CLIENTTOKEN_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:40: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:39: multiple definition of `GOWHATSAPP_SESSION_CLIENDID_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:39: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:34: multiple definition of `GOWHATSAPP_PREVIOUS_SESSION_TIMESTAMP_KEY'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:34: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:29: multiple definition of `GOWHATSAPP_INLINE_IMAGES_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:29: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:28: multiple definition of `GOWHATSAPP_DOWNLOAD_TRY_ONLY_ONCE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:28: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:27: multiple definition of `GOWHATSAPP_DOWNLOAD_ATTACHMENTS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:27: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:26: multiple definition of `GOWHATSAPP_SYSTEM_MESSAGES_ARE_ORDINARY_MESSAGES_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:26: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:25: multiple definition of `GOWHATSAPP_TIMESTAMP_FILTERING_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:25: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:24: multiple definition of `GOWHATSAPP_MESSAGE_ID_STORE_SIZE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:24: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:23: multiple definition of `GOWHATSAPP_FAKE_ONLINE_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:23: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:22: multiple definition of `GOWHATSAPP_PLAIN_TEXT_LOGIN'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:22: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:21: multiple definition of `GOWHATSAPP_GET_ICONS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:21: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:20: multiple definition of `GOWHATSAPP_FETCH_CONTACTS_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:20: first defined here
/usr/bin/ld: gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:19: multiple definition of `GOWHATSAPP_RESTORE_SESSION_OPTION'; gwa-to-purple.o:/tmp/purple-gowhatsapp/constants.h:19: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:54: purplegwa.a] Error 2
```

**Comment by hoehermann** [comment]
@leolca Your issue looks more like #57. Are you using Slackware by any chance?

**Comment by leolca** [comment]
@hoehermann I'm using Ubuntu 20.04. I've read #57 and it seems it is still an open problem, right?

**Comment by hoehermann** [comment]
@leolca It is an unresolved issue I fail to reproduce on Ubuntu 18.04. Maybe I can reproduce on Ubuntu 20.04 (and possibly solve it for both distros).

**Comment by hoehermann** [comment]
@leolca I just compiled it successfully on a freshly installed Ubuntu 20.04. Using golang-go, not gccgo-go.

**Comment by leolca** [comment]
Indeed. I could compile with no errors... but after copying ```libgowhatsapp.so``` into ```~/.purple/plugins/``` folder I get ```Segmentation fault (core dumped)``` after reading the QR code.

**Comment by hoehermann** [comment]
@EionRobb I just double checked all situations I am handling the connection identifier. I have not spotted any line I am passing it incorrectly. That would mean the `PurpleConnection *` returned by `purple_account_get_connection(…)` has been `NULL` during login. Regardless whether I _should_, I do not really _want_ to check every value returned by libpurple for consistency. I do not see any other plug-in doing so. Even if I guarded the plug-in from accessing a null-pointer, it would still be useless. And it works for me and many other people. I suspect there is something wrong with lelolca's build.
