### ISSUE TITLE
Pidgin crash after scanning QR code

### ISSUE THREAD

**Issue by gbasisty** [hoehermann/purple-gowhatsapp#61]
Hi! 
I have compiled the source code with no errors and the plugin is now on ~/.purple/plugins/libgowhatsapp.so
When I run pidgin, it shows the QR code, and after I scann it with my phone, pidgin crushes with the following error message:

munmap_chunk(): invalid pointer
[1]    1660 abort      pidgin

Debian 10 amd_64 here.
Any ideas? 

Best regards, and thank you in advance.-

**Comment by hoehermann** [comment]
Thank you for the report. This looks like #52. Maybe related to #53 or #56, too. It does not happen to me so I cannot reproduce this issue for purpose of investigating. :(

**Comment by lienardj** [comment]
Got the same problem. Which version of pidgin do you use? I'm using 2.13 on Ubuntu 20.04.

**Comment by hoehermann** [comment]
Finally, a crash right after login happened to me, too.

@lienardj @gbasisty @alcmoraes @AllwinSamuelJeba @pkar70 @leolca Is version 0.3.0 (current master at commit 5626858) working for you? Binaries are available at https://buildbot.hehoe.de/purple-gowhatsapp/builds/.

**Comment by leolca** [comment]
Sorry... but still crashing. I've tried the nightly build and I've tried to compile from the source. Both have crashed.

**Comment by lienardj** [comment]
Hi, the same. I have two account, one with just around 100 contacts, another with 700-800 contacts.

The problem occurs when I activate the other account, with 700-800 contacts. I don't have the problem with the build "libgowhatsapp_0.2.0~git485f60e+gowhatsapp~git5e33cb4_amd64_ubuntu18.04.so" from the 2020-05-01.

Result of `$ pidgin -d > pidgin-log.txt`
[pidgin-log.txt](https://github.com/hoehermann/purple-gowhatsapp/files/4947402/pidgin-log.txt)

**Comment by hoehermann** [comment]
Dang it.

> I don't have the problem with the build `libgowhatsapp_0.2.0~git485f60e+gowhatsapp~git5e33cb4_amd64_ubuntu18.04.so` from the 2020-05-01.

That is very valuable information. Thank you very much. It means the problem is somewhere in the proxy support. I am not typically using a proxy myself – that is probably why the crash does not happen on my system. I want to do some investigation.

**Comment by lienardj** [comment]
No, I don't use a proxy. I have configured both account with "no proxy", still crashing.

**Comment by hoehermann** [comment]
I still cannot find the cause of this issue over here on my computer.

However, as this problem affects relatively many users, I feel motivated to solve it. I am willing to enter a remote debugging session with any of you. Preferably someone who compiles the plug-in themselves. I imagine we enter a video chat, share a screen via Skype/Discord/whatever or a terminal session via tmate or local ssh server. You can then watch me as I develop/debug on your system. You should probably create a new local account so I do not have direct access to your data (apart from your WhatsApp account). Have gdb installed. Prepare to scan the QR code often and hear a lot of cussing. Send a mail to hoehermann@gmx.de if you are interested.

**Comment by hoehermann** [comment]
@lienardj kindly helped me do some investigation. I am very grateful. It looks like at one critical point I have been mistaking garbage-collected memory (managed by Go) for heap-allocated memory ("managed" by C) for the past year. It is a miracle this was working at all.

@lienardj @Industry @gbasisty @alcmoraes @AllwinSamuelJeba @pkar70 @leolca @brianjmurrell – does version 0.3.2 eliminate or reduce crashes for you? Please test and report, if possible. Binaries for Ubuntu 18.04 and Windows are available at https://buildbot.hehoe.de/purple-gowhatsapp/builds/.

**Comment by leolca** [comment]
it works! :+1:  :-)

**Comment by lienardj** [comment]
It's working. I didn't got a crash for the whole day.

Great job!

**Comment by hoehermann** [comment]
Reported fixed.
