### ISSUE TITLE
Pidgin crashes when enabling "Download files from media (image, audio, video, document) messages"

### ISSUE THREAD

**Issue by Industry** [hoehermann/purple-gowhatsapp#62]
As soon as this option is enabled and WhatsApp is active, the application crashes. If it is enabled at launch, pidgin uses a lot of CPU and crashes after ~5 seconds.
Happy to provide some logs and more information, just tell me what would be most useful.

Also worth mentioning that everytime Pidgin starts, a message box like this appears: [Screenshot](https://i.imgur.com/5aTKJoA.png)
I believe this to be the ~10 media messages that I have sent to myself in the past. This appears with every launch.

**Comment by hoehermann** [comment]
@lienardj helped me do some investigation. I noticed I might be mistaking garbage-collected memory for heap-allocating at one critical point. I want to sort this out, then release a new version. It might fix a lot of bugs.

**Comment by Industry** [comment]
You're right the issue has gone away with an update to a newer build! Thanks

**Comment by hoehermann** [comment]
Glad to hear that. Thank you for reporting back. :)
