### ISSUE TITLE
Sending file (picture) - by copying path

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#65]
Although I don't know if it is in WhatsApp plugin or in Piding as such...

Using Windows Explorer, I can right click file, and choose "Copy path" from context menu. But filepath is enclosed in quotes, and when I'm trying to paste it to file browser (Send file...), nothing happens. I have to paste this path in e.g. notepad, delete opening and ending quotes, copy path (without quotes), and paste it in file browser.

Could file browser simply "strip" quotes?

**Comment by hoehermann** [comment]
Just so I understand the problem correctly: This is only when copying a path from the Explorer, right? 
Selecting the file manually in the "send file" dialogue is working? Dragging the file into the conversation window should work, too.

I really do not want to mangle local paths. If a third party application (in this case the Windows Explorer) presents file paths which are not considered valid by the very same operating system it comes with, that is not this plug-in's job to clean it up. If you want the GTK file chooser to adjust the path provided, you can ask the people at the [GTK project](https://www.gtk.org/community/). I doubt they will include it in GTK2, though. GTK3 maybe, but that will only impact Pidgin 3 (if that ever gets released).

**Comment by pkar70** [comment]
I know that you closed issue :) but just explaining.
In Windows command line, every parameter/file can be placed in quotes; and every parameter/filename with spaces within have to be placed inside quotes. Yes, CopyPath command could, when filepathname is without spaces, do not use quotes. 
When I use path with quotes in FileOpen dialog (e.g. in NOTEPAD), it opens file. Also Word can open file using such filepathname.

**Comment by EionRobb** [comment]
Protocol plugins, such as the WhatsApp plugin, have no control over user interface such as file picker dialogues and wouldn't be able to change the behaviour of the GTK one even if it wanted to

**Comment by pkar70** [comment]
I only responded to "not considered valid" :)

**Comment by hoehermann** [comment]
Your request is very understandable. The behaviour annoys me, too, every time I need to use Windows. Sometimes it works, sometimes it does not (cmd, PowerShell and Python seem to disagree a lot on this). I do not want to come across as dismissive, but I also need to keep the scope from exploding. ;)
