### ISSUE TITLE
"Unable to send message" - please add failed message

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#66]
Sometimes I got:

Unable to send message
Unable to send message: sending message timed out

First line is in red, second - black.

Could you add failed message to this error message?
E.g. when I try to send "lorem ipsum", error message could be:
Unable to send message: lorem ipsum

So, I can copy/paste message and try to send it again (although almost always message is sent, as can be seen in WhatsApp on phone).

**Comment by kevenwyld** [comment]
I get the same error but if I go look at the conversation on my phone the message has been sent anyway every time, despite the time out message.  Is this the same for you?

**Comment by pkar70** [comment]
Almost :)
I almost never check if message is really sent; but sometimes, when I don't have answer for some time, I'm checking on phone. One time message was really not sent.

**Comment by hoehermann** [comment]
@pkar70 Is 8df1101 to your liking?

**Comment by pkar70** [comment]
Probably :)
(guessing from code)

But I'm waiting for "nightly build" with this patch :)
