### ISSUE TITLE
auto reconnection

### ISSUE THREAD

**Issue by javi2man** [hoehermann/purple-gowhatsapp#67]
i want this plugin to auto reconnect itself when the internet connection goes off by any reason ´cause i have to connect each time manually and it 's so annoying. Thanks!

**Comment by hoehermann** [comment]
Before I start searching far and wide, I rather ask @EionRobb: Is there a Purple plug-in or libpurple mechanism for this? As in "disconnect and switch to connecting immediately". I'd rather use an established global scheme rather than implement this on protocol plug-in level.

**Comment by EionRobb** [comment]
Yep, in the disconnect reason code, if you specify one that doesn't cause the account to be disabled then it'll auto reconnect to the account after a minute or so

**Comment by hoehermann** [comment]
@javi2man Is 45ea98e to your liking?
