### ISSUE TITLE
What will happen to this plugin with the new multi device mode that whatsapp 'll implement?

### ISSUE THREAD

**Issue by javi2man** [hoehermann/purple-gowhatsapp#68]
i've read this article and i wondered if this 'll have impact to this plugin. 
https://translate.google.com/translate?sl=es&tl=en&u=https%3A%2F%2Fwww.genbeta.com%2Fmensajeria-instantanea%2Fasi-sera-modo-multidispositivo-whatsapp-cuatro-dispositivos-rediseno-version-escritorio
Thanks in advance

**Comment by hoehermann** [comment]
I expect https://github.com/Rhymen/go-whatsapp to handle this mode. This plug-in is just glue to Pidgin/libpurple. Apart from that, I do not make assumptions about the future of this plug-in.
