### ISSUE TITLE
Pidgin plugin not loaded

### ISSUE THREAD

**Issue by l154** [hoehermann/purple-gowhatsapp#7]
Hi
I can't create an account
when starting pidgin i have an error
01:05:10) plugins: probing /home/xxx/.purple/plugins/libgowhatsapp.so
(01:05:10) plugins: /home/xxx/.purple/plugins/libgowhatsapp.so is not loadable: undefined symbol: unsafe.Pointer..d
Pidgin version: pidgin-2.13
Can you send me libgowhatsup.so ??

**Comment by sajeshcherian** [comment]
https://my.pcloud.com/publink/show?code=kZfEvE7Zy467h6yJjqY57sA6GVE9bL8hIxVk

I generated this binary and it works fine on my Ubuntu machine.

**Comment by l154** [comment]
HiYour library works like a harm thank you
br MS
W dniu śro, 17.04.2019 o godzinie 16∶55 -0700, użytkownik Sajesh
Cherian napisał:

**Comment by hoehermann** [comment]
I cannot reproduce this problem. I suspect an issue within your specific compilation process.
