### ISSUE TITLE
Download friendly names

### ISSUE THREAD

**Issue by ellingtonsantos** [hoehermann/purple-gowhatsapp#71]
Hi! I got this plugin to work with bitlbee after send qrcode to a file and scanning from there.

But I couldn't get friendly display names (the are phone numbers).

Could you help me to simplify this scenario?

**Comment by hoehermann** [comment]
As of now, this plug-in does not download the friendly names.

**Comment by hoehermann** [comment]
The whatsmeow branch does download the friendly names.
