### ISSUE TITLE
"Unable to send message" - "Allegedly", and messages log

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#72]
As continuation of
"Unable to send message" - please add failed message #66

Can this "allegedly" message be sent to log (of chat) instead current error message?
As most often message is really sent, I don't repeat it. Although messages log on screen is full, log contains only "Unable to send message.". And, as I frequently use 'view log/search', I'd welcome log with even allegedly lost message.

Sometimes, message is not sent, and I can resend it, using copy/paste from log visible on screen.

**Comment by hoehermann** [comment]
The text "Unable to send message" is displayed by Pidgin. It is Pidgin's decision not to store messages which were not sent. I cannot change the logic at that point. 

The more detailed line with "allegedly" should end up in the log if you check "Treat system messages like normal messages" in the plug-in's extended options.

**Comment by hoehermann** [comment]
Closing due to lack of response.
