### ISSUE TITLE
Does this plugin allow for video conferencing?

### ISSUE THREAD

**Issue by Geremia** [hoehermann/purple-gowhatsapp#73]
Does this plugin allow for WhatsApp video conferencing in Pidgin?

**Comment by hoehermann** [comment]
No. As far as I can tell from the [Business API Documentation](https://developers.facebook.com/docs/whatsapp/api/reference), video calls are not supported by WhatsApp Web.

**Comment by Geremia** [comment]
@hoehermann  Thanks. That's too bad.
