### ISSUE TITLE
Question: ability to stay logged in web.whatsapp.com while using gowhatsapp

### ISSUE THREAD

**Issue by Industry** [hoehermann/purple-gowhatsapp#76]
Every time I login to pidgin, the website version logs out [screenshot](https://i.imgur.com/iQ4qeUa.png) and I can't tell if this is a misconfiguration where they are sharing the same login details or there is no way to use them simultaneously. 

It's possible to use the web.whatsapp.com on multiple computers at once without being forced to log out, so I was thinking it's probably an issue on my end.

Thanks!

**Comment by hoehermann** [comment]
> It's possible to use the web.whatsapp.com on multiple computers at once without being forced to log out

How do you do that? I cannot confirm this being possible. As soon as I open web.whatsapp.com on a second computer or browser, the first one disconnects immediately.

The session is never terminated automatically unless I click the button.

**Comment by Industry** [comment]
You're right, can't use the web version at two locations at the same time. I mistakenly thought it was possible because the app showed me a few locations logged in at once -- it was merely different browsers I had scanned the QR codes in from.

In any event it's one or the other: web or gowhatsapp?

**Comment by hoehermann** [comment]
Yes. To the official WhatsApp on the phone, it does not matter if one uses a browser or gowhatsapp. It always is "one connection at a time". Cumbersome, but that is how WhatsApp inc. wants it to be. :/

**Comment by Industry** [comment]
Guess it's a limitation of the service then. Thanks for the information
