### ISSUE TITLE
Login without QR code

### ISSUE THREAD

**Issue by piggz** [hoehermann/purple-gowhatsapp#78]
Hi, just wondering if its possible to log in without using whatsapp to scan a QR code, I thought it was supported but couldnt see how to do it.

I appreciate my use case it a but of a corner case.  My primary phone runs sailfish, and the android layer on this particular phone doesnt have camera access, so I cant actually scan a code!

If its not possible then i guess im just out of luck!

Thanks

**Comment by hoehermann** [comment]
I face the same problem with WhatsApp running in [anbox](https://anbox.io/). go-whatsapp (and as a result this plug-in) have access to the raw data which is usually represented as a QR code. The software does not care about how this code finds its way into the phone. As far as I know, the official WhatsApp client is "QR code via camera" only. No alternatives are provided. In case I am wrong or the situation changes, please re-open this issue.
