### ISSUE TITLE
Old messages notified many times

### ISSUE THREAD

**Issue by rogora** [hoehermann/purple-gowhatsapp#8]
Is there a good reason why this plugin is using ids to identify messages already received? The list of ids, as it is stored right now, is cumbersome, and is truncated quickly. As a result, when this plugin disconnects from whatsapp and the reconnects, it happens often that old messages are shown again, as new. 

I think that keeping a timestamp of the most recent received message, and accepting new messages only if newer than the timestamp, is way lighter and safer. There might be the chance of missing messages (but I'm not sure, and I guess the event is extremely rare), but I think it would still be better than the current approach.

**Comment by hoehermann** [comment]
I chose the IDs since the server does not always send old messages. If it does, they are sent per contact and in seemingly random order. This usually happens right after connecting, but sometimes, it takes a couple of seconds until the initial burst of messages is over. In case of large images on a slow connection, it may be a longer duration.

A message displayed twice is annoying. A dropped message can be may way more annoying (think of a missed appointment). I want to be on the safe side.

As a quick solution, I made the number of messages remembered user-configurable and increased the default.

As always: Pull requests are welcome. :) Just add your approach and an option for the user to chose from in the settings.

**Comment by rogora** [comment]
Ok, thanks for response. I hadn't realized that the problem was only during the connection phase. This makes things easier to handle. 
I created a pull request which filters messages with a timestamp that is older (or equal) than the most recent message received in the last session, that is before the current connection. In this way we do not risk to filter unread messages due to reordering when the connection is established.

**Comment by hoehermann** [comment]
Thank you for your contribution. However, I see a problem with `session_most_recent_ts` being global.

#### Messages may get lost

Consider the following scenario:

* I am offline.
* Alice sends a message at 1 (example timestamp value).
* Bob sends a message at 2.
* Alice sends a message at 3.
* I go online.  
  The server sends offline messages in random order:
  1. Message from Alice sent at 3.
  2. Message from Alice sent at 1.
  3. Message from Bob sent at 2.
* During receival of the first message, `session_most_recent_ts` will be set to 3 in line 104. Consequently, the other messages are discarded.

#### Affecting all connections

`session_most_recent_ts` is global for all gowhatsapp connections (imagine having two phones). A relatively new message received on one phone will suppress slightly older messages received on the other phone.

**Comment by rogora** [comment]
Thank you for your feedback, but I'm not sure I understand your concern.

Regarding the lost messages problem, in the scenario that you describe, message would not be lost. It is true that in line 104 session_most_recent_ts is set, but the new value will be read only at the beginning of a new connection. Ideally, it would be possible to set session_most_recent_ts only when the disconnection happens, but I wanted to be safe in case of crashes of other unexpected problems. Messages 1, 2, and 3 would not be discarded because they would all have a timestamp that is newer than the timestamp of the last message received in the last session. 

About the session_most_recent_ts being global problem... I do not understand this. I think that one instance of the plugin is always supposed to handle one connection to one whatsapp web server at any given time. If you have more whatsapp web servers that you want to connect to, then you have many independent instances of the plugin running. Am I wrong?

**Comment by EionRobb** [comment]
One instance of the plugin can have many accounts connected to it.  Each account should have its own most recent timestamp, but you've made it so that if you have 5 accounts, all 5 would share the same timestamp

**Comment by rogora** [comment]
Mmmh, interesting... that there are many details in the structure of libpurple that I do not know.
Thanks for the feedback, I updated the pull request accordingly.
