### ISSUE TITLE
Building fails on Arch Linux

### ISSUE THREAD

**Issue by 0zuna** [hoehermann/purple-gowhatsapp#82]
REBUILD
$ make update-dep
fatal: no es un repositorio git: '/purple-gowhatsapp/go/src/github.com/Rhymen/go-whatsapp/.git'
go get -u github.com/skip2/go-qrcode
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go get -u github.com/gabriel-vasile/mimetype
go: downloading github.com/gabriel-vasile/mimetype v1.3.0
go: downloading golang.org/x/net v0.0.0-20210505024714-0287a6fb4125
go: downloading golang.org/x/net v0.0.0-20210614182718-04defd469f4e
go get -u github.com/Rhymen/go-whatsapp
go: downloading github.com/Rhymen/go-whatsapp v0.1.1
go: downloading github.com/gorilla/websocket v1.4.1
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/golang/protobuf v1.3.0
go: downloading golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: downloading google.golang.org/protobuf v1.26.0
touch -d "" /home/dimitri/programs/purple-gowhatsapp/go/pkg/linux_amd64/github.com/Rhymen/go-whatsapp.a
touch: no se puede efectuar `touch' sobre '/home/dimitri/programs/purple-gowhatsapp/go/pkg/linux_amd64/github.com/Rhymen/go-whatsapp.a': No existe el fichero o el directorio
make: *** [Makefile:45: update-dep] Error 1

**Comment by 0zuna** [comment]
log from old bin gowhatsapp.so:
error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by hoehermann** [comment]
> fatal: no es un repositorio git: '/purple-gowhatsapp/go/src/github.com/Rhymen/go-whatsapp/.git'

GOPATH seems to be pointing to a non-existent location. Please check your local build environment. A build-bot provides updated [nightly binaries](https://buildbot.hehoe.de/purple-gowhatsapp/builds/) for Ubuntu 20.04 which may work on other distributions, too.

> cannot unmarshal array into Go value of type map[string]interface {}

This is a by-product of go-whatsapp using an outdated version string. Mentioned in #81.

**Comment by 0zuna** [comment]
> GOPATH seems to be pointing to a non-existent location. Please check your local build environment. A build-bot provides updated [nightly binaries](https://buildbot.hehoe.de/purple-gowhatsapp/builds/) for Ubuntu 20.04 which may work on other distributions, too.
i am get:
error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
from the last [binaries](https://buildbot.hehoe.de/purple-gowhatsapp/builds/)

GOPATH is in makefile:
export GOPATH?=$(CURDIR)/go

i get this in only make:

[dimitri@nabuconodosor purple-gowhatsapp]$ make
go get github.com/Rhymen/go-whatsapp
go get github.com/skip2/go-qrcode
go get github.com/gabriel-vasile/mimetype
go build -buildmode=c-archive -o purplegwa.a purplegwa.go purplegwa-media.go
purplegwa.go:87:2: no required module provides package github.com/Rhymen/go-whatsapp: go.mod file not found in current directory or any parent directory; see 'go help modules'
purplegwa-media.go:29:2: no required module provides package github.com/gabriel-vasile/mimetype: go.mod file not found in current directory or any parent directory; see 'go help modules'
purplegwa.go:88:2: no required module provides package github.com/pkg/errors: go.mod file not found in current directory or any parent directory; see 'go help modules'
purplegwa.go:89:2: no required module provides package github.com/skip2/go-qrcode: go.mod file not found in current directory or any parent directory; see 'go help modules'
make: *** [Makefile:54: purplegwa.a] Error 1

**Comment by 0zuna** [comment]
hello @hoehermann
i tried today the current binari from [nightly binaries](https://buildbot.hehoe.de/purple-gowhatsapp/builds/)
rename current to current.so and only this is working (current date 2021-06-16 00:30).
only this is working with the last updates
i am working in ArchLinux
Thanks n.n

**Comment by hoehermann** [comment]
> rename current to current.so and only this is working (current date 2021-06-16 00:30).

Good to hear that the binary is working for you.

> i am working in ArchLinux

I cannot possibly provide assistance to build on all the distributions, so I focus on Ubuntu only. Reports on the [AUR](https://aur.archlinux.org/packages/purple-gowhatsapp-git/) state building fails on Arch Linux. A patch is provided, but I should install Arch Linux to test it myself. I probably will not be doing that anytime soon. Pull requests are welcome.

**Comment by 0zuna** [comment]
hello @hoehermann i resolved the bug please accept the pull request n.n

**Comment by 0zuna** [comment]
thanks for accept this resolve the problem in [AUR](https://aur.archlinux.org/packages/purple-gowhatsapp-git/)
