### ISSUE TITLE
Does not work on WinXP

### ISSUE THREAD

**Issue by StugotzCapisc** [hoehermann/purple-gowhatsapp#91]
Hello I downloaded the last nighly build of purple-gowhatsapp for Windows, put the bin file in the plugins folder but Pidgin doesn't even launch. Why? Thanks in advance

P.s. i'm using Pidgin 2.14.1 on Win XP

**Comment by EionRobb** [comment]
Can you run pidgin from a command prompt with `pidgin.exe -d` and put the output here?

**Comment by StugotzCapisc** [comment]
C:\Documents and Settings\******>start pidgin.exe -d

C:\Documents and Settings\******>Loaded exchndl.dll
 Setting exchndl.dll LogFile to C:\DOCUME~1\******\IMPOST~1\Temp\pidgin.RPT
 Setting exchndl.dll DebugInfoDir to C:\Programmi\Pidgin\pidgin-2.14.1-dbgsym
GTK+ path found: C:\Programmi\Pidgin\Gtk\bin
Using SetDllDirectory
Setting locale: LANG=it
(19:27:33) wpurple: Purple settings dir: C:\Documents and Settings\******\Dati
 applicazioni
(19:27:33) winpidgin: winpidgin_init start
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\exchndl.dll contains Set
LogFile
(19:27:33) winpidgin: Setting exchndl.dll LogFile to C:\Documents and Settings\G
ianluca\Dati applicazioni\.purple\pidgin.RPT
(19:27:33) wpurple: C:\Programmi\Pidgin\spellcheck\libgtkspell-0.dll not already
 loaded; loading it...
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_new_attach
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_get_from_text_view
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_detach
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_set_language
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_recheck_all
(19:27:33) winpidgin: GTK+ :2.16.6
(19:27:33) winpidgin: winpidgin_init end
(19:27:33) wpurple: wpurple_init start
(19:27:33) wpurple: libpurple version: 2.14.1
(19:27:33) wpurple: Glib:2.28.8
(19:27:33) wpurple: wpurple_init end
(19:27:33) prefs: Reading C:\Documents and Settings\******\Dati applicazioni\.
purple\prefs.xml
(19:27:33) prefs: Finished reading C:\Documents and Settings\******\Dati appli
cazioni\.purple\prefs.xml
(19:27:33) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\autoaccept.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\buddynote.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\convcolors.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\extplacement.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\gtkbuddynote.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\history.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\iconaway.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\idle.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\joinpart.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libaim.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libbonjour.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libfacebook.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libgg.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libgowhatsapp.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libicq.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libirc.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libnovell.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libsametime.dll
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Im
possibile trovare la procedura specificata.

(19:27:33) plugins: C:\Programmi\Pidgin\plugins\libsametime.dll has a prefs_info
, but is a prpl. This is no longer supported.
goroutine 1(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libsilc.dll
 [running]:
syscall.(*LazyProc).mustFind(0x208399e0)
        c:/go/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x208399e0, 0x1c703e8)
        c:/go/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x1d4, 0x9, 0x20867e54, 0x
8, 0x180854c, 0x20868580)
        c:/go/src/internal/syscall/windows/zsyscall_windows.go:385 +0x27
os.newFileStatFromGetFileInformationByHandle(0x20812240, 0x1e, 0x1d4, 0x0, 0x208
12240, 0x1e)
        c:/go/src/os/types_windows.go:52 +0x113
os.(*File).Stat(0x208065c0, 0x208101e0, 0x0, 0x0, 0x208065c0)
        c:/go/src/os/stat_windows.go:37 +0x128
google.golang.org/protobuf/internal/detrand.binaryHash(0x0, 0x0)
        Z:/var/www/www-buildbot/html/purple-gowhatsapp/source/go/src/google.gola
ng.org/protobuf/internal/detrand/rand.go:56 +0xdd
google.golang.org/protobuf/internal/detrand.init()
        Z:/var/www/www-buildbot/html/purple-gowhatsapp/source/go/src/google.gola
ng.org/protobuf/internal/detrand/rand.go:38 +0x1a

**Comment by StugotzCapisc** [comment]
> Can you run pidgin from a command prompt with `pidgin.exe -d` and put the output here?

C:\Documents and Settings******>start pidgin.exe -d

C:\Documents and Settings*>Loaded exchndl.dll
Setting exchndl.dll LogFile to C:\DOCUME~1*\IMPOST~1\Temp\pidgin.RPT
Setting exchndl.dll DebugInfoDir to C:\Programmi\Pidgin\pidgin-2.14.1-dbgsym
GTK+ path found: C:\Programmi\Pidgin\Gtk\bin
Using SetDllDirectory
Setting locale: LANG=it
(19:27:33) wpurple: Purple settings dir: C:\Documents and Settings*\Dati
applicazioni
(19:27:33) winpidgin: winpidgin_init start
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\exchndl.dll contains Set
LogFile
(19:27:33) winpidgin: Setting exchndl.dll LogFile to C:\Documents and Settings\G
ianluca\Dati applicazioni.purple\pidgin.RPT
(19:27:33) wpurple: C:\Programmi\Pidgin\spellcheck\libgtkspell-0.dll not already
loaded; loading it...
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_new_attach
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_get_from_text_view
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_detach
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_set_language
(19:27:33) wpurple: This version of C:\Programmi\Pidgin\spellcheck\libgtkspell-0
.dll contains gtkspell_recheck_all
(19:27:33) winpidgin: GTK+ :2.16.6
(19:27:33) winpidgin: winpidgin_init end
(19:27:33) wpurple: wpurple_init start
(19:27:33) wpurple: libpurple version: 2.14.1
(19:27:33) wpurple: Glib:2.28.8
(19:27:33) wpurple: wpurple_init end
(19:27:33) prefs: Reading C:\Documents and Settings*\Dati applicazioni.
purple\prefs.xml
(19:27:33) prefs: Finished reading C:\Documents and Settings******\Dati appli
cazioni.purple\prefs.xml
(19:27:33) prefs: purple_prefs_get_path: Unknown pref /pidgin/browsers/command
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\autoaccept.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\buddynote.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\convcolors.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\extplacement.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\gtkbuddynote.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\history.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\iconaway.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\idle.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\joinpart.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libaim.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libbonjour.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libfacebook.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libgg.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libgowhatsapp.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libicq.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libirc.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libnovell.dll
(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libsametime.dll
panic: Failed to find GetFileInformationByHandleEx procedure in kernel32.dll: Im
possibile trovare la procedura specificata.

(19:27:33) plugins: C:\Programmi\Pidgin\plugins\libsametime.dll has a prefs_info
, but is a prpl. This is no longer supported.
goroutine 1(19:27:33) plugins: probing C:\Programmi\Pidgin\plugins\libsilc.dll
[running]:
syscall.(*LazyProc).mustFind(0x208399e0)
c:/go/src/syscall/dll_windows.go:311 +0x42
syscall.(*LazyProc).Addr(0x208399e0, 0x1c703e8)
c:/go/src/syscall/dll_windows.go:318 +0x21
internal/syscall/windows.GetFileInformationByHandleEx(0x1d4, 0x9, 0x20867e54, 0x
8, 0x180854c, 0x20868580)
c:/go/src/internal/syscall/windows/zsyscall_windows.go:385 +0x27
os.newFileStatFromGetFileInformationByHandle(0x20812240, 0x1e, 0x1d4, 0x0, 0x208
12240, 0x1e)
c:/go/src/os/types_windows.go:52 +0x113
os.(*File).Stat(0x208065c0, 0x208101e0, 0x0, 0x0, 0x208065c0)
c:/go/src/os/stat_windows.go:37 +0x128
google.golang.org/protobuf/internal/detrand.binaryHash(0x0, 0x0)
Z:/var/www/www-buildbot/html/purple-gowhatsapp/source/go/src/google.gola
ng.org/protobuf/internal/detrand/rand.go:56 +0xdd
google.golang.org/protobuf/internal/detrand.init()
Z:/var/www/www-buildbot/html/purple-gowhatsapp/source/go/src/google.gola
ng.org/protobuf/internal/detrand/rand.go:38 +0x1a

**Comment by EionRobb** [comment]
Looks like an issue in golang, but it looks like go stopped working in winxp as of go 1.12 - you could try recompiling yourself with an older version of golang or use an older version of the plugin

**Comment by StugotzCapisc** [comment]
> Looks like an issue in golang, but it looks like go stopped working in winxp as of go 1.12 - you could try recompiling yourself with an older version of golang or use an older version of the plugin

I tried this old version:
https://github.com/hoehermann/purple-gowhatsapp/files/4449243/libgowhatsapp.zip

Now Pidgin get started but I can't login because it gives me this error:

error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

I don't know how to do 😟

**Comment by hoehermann** [comment]
> it looks like go stopped working in winxp

Yes, this seems to be a problem, as discussed here: https://github.com/golang/go/issues/30588 Maybe I can downgrade the go compiler on the build-system accordingly.

**Comment by StugotzCapisc** [comment]
> > it looks like go stopped working in winxp
> 
> Yes, this seems to be a problem, as discussed here: [golang/go#30588](https://github.com/golang/go/issues/30588) Maybe I can downgrade the go compiler on the build-system accordingly.

Thank you, I'd really appreciate it 👍
