### ISSUE TITLE
Cannot login to WhatsApp server

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#93]
Today (2 XI 2021) I got:
`restoring failed: error decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {}`
I tried several times to 'Re-enable', but problem still persist.

**Comment by lazyest** [comment]
confirm

**Comment by lazyest** [comment]
I've played a bit with different advises making from sources with different client version numbers with no luck :(

**Comment by hoehermann** [comment]
This is probably related to https://github.com/Rhymen/go-whatsapp/issues/627 and will be resolved with the next go-whatsapp release. [Nightly builds](https://buildbot.hehoe.de/purple-gowhatsapp/builds/?C=M;O=D) are updated automatically.

Although #81 comes to mind again. With any luck, I find motivation to work on this plug-in again one day.

**Comment by hoehermann** [comment]
This was fixed with https://github.com/Rhymen/go-whatsapp/commit/31a2e740845cad68f209d41b01c39983491ba566.

**Comment by pkar70** [comment]
By the way... I don't know what response is sent by server, but maybe there is minimum client version allowed?
If yes, than gowhatsapp can auto-adjust version number sent to server.

**Comment by hoehermann** [comment]
I hope these version numbers do not only exist to annoy us, but actually are necessary due to feature or protocol changes. This means that go-whatsapp and consequently the plug-in must be updated on a regular basis to ensure functionality. Daftly claiming to be compatible with an appropriate version without actually understanding what kind of new stuff the server is throwing at us won't help much. ;)

**Comment by pkar70** [comment]
Of course new version mean new functionality, sometimes maybe broken backward compatibility. But:
a) go-whatsapp supports only basic functionality, so probability of broken compatibility is not big;
b) it can be MessageBox: "plugin was compiled for version XXX, WhatsApp server requires version YYYY, do you want to try?"

**Comment by hoehermann** [comment]
Understood. I want to keep it in mind in the context of #81.
