### ISSUE TITLE
JSON unmarshalling errors -- client version change needed

### ISSUE THREAD

**Issue by matthewhague** [hoehermann/purple-gowhatsapp#94]
See [this upstream bug](https://github.com/Rhymen/go-whatsapp/issues/633).

The current fix is to add the line

    wac.SetClientVersion(3, 2123, 7)

Putting this before handler.wac = wac in the connect_and_login method in purplegwa.go works, though maybe there's a better place.

I've done this on my own version [here](https://github.com/yourealwaysbe/purple-gowhatsapp/commit/98a74d2a3c86617d47fa3cf6dd80b87ad56d0147).

**Comment by hoehermann** [comment]
Thank you for the report. The issue has been brought up at #93 and option for setting the client version suggested at #81.

**Comment by matthewhague** [comment]
Sorry, apologies for noise!

**Comment by hoehermann** [comment]
No problem. :)
