### ISSUE TITLE
QR pairing required on every login

### ISSUE THREAD

**Issue by blacklight** [hoehermann/purple-gowhatsapp#96]
I have recently made a small Perl script for my irssi+bitlbee setup that automatically displays the pairing QR code when pairing is required:

```perl
# purple-gowhatsapp-login.pl
# based on espeakeasy.pl
%PLUGIN_INFO = (
    perl_api_version => 2,
    name => "purple-gowhatsapp-login",
    version => "0.1",
    summary => "TODO",
    description => "TODO",
    author => "Fabio Manganiello",
    url => "",
    load => "plugin_load",
    unload => "plugin_unload",
);

sub plugin_init {
    return %PLUGIN_INFO;
}

sub plugin_unload {
    my $plugin = shift;
}

sub on_privmsg {
    my ($server, $data, $nick, $address, $target) = @_;

    if ($address eq 'login@s.whatsapp.net') {
        $data =~ s/.*Login data for WhatsApp account [0-9]+\@s.whatsapp.net:\s*(.+?)<img id="\d+">/$1/;
        system(("qrencode \"$data\" -o - | feh - &"));
    }
}

Irssi::signal_add ("event privmsg" => \&on_privmsg);
```

It works great, the problem is that the QR code is displayed every time I log out and log in again, or simply restart irssi.

I thought it was some problem with my script, but even without it gowhatsapp requires new authentication on every login.

Is it a known issue? Is it something specific to gowhatsapp on bitlbee? Or did I miss something obvious with my setup or script?

**Comment by hoehermann** [comment]
This is or rather _was_ a known problem. yourealwaysbe kindly provided ad341fbe. To overcome this very problem, the commit changes the password storage location specifically geared towards bitlbee. I do not use/test with bitlbee. Maybe @yourealwaysbe can help.

**Comment by yourealwaysbe** [comment]
Have you set "restore-session" to "true"?

I haven't tested it lately (my original login is still restoring ok from ages ago).

At some point i'd planned on writing a user guide for BitlBee since there are a couple of non-obvious settings. This Perl script would be a good addition.

**Comment by blacklight** [comment]
@yourealwaysbe thanks for the response. I have been using [`purple-gowhatsapp-git`](https://aur.archlinux.org/packages/purple-gowhatsapp-git/) installed via AUR. I see that that package currently points to commit [`438fae6`](https://github.com/hoehermann/purple-gowhatsapp/commit/438fae6d6742c364e8f1bc16744846265506ea30), which is just a few days earlier than [`ad341fbe`](https://github.com/hoehermann/purple-gowhatsapp/commit/ad341fbe0a31c1088c976ecfb6ab522312baaab4).

After uninstalling the AUR package and building the latest executable I confirm that the issue is gone.

Not sure who the maintainer of the AUR package is, but maybe it's worth updating it?

**Comment by hoehermann** [comment]
Probably. I do not know how to contact GI_Jack either. Anyway, the issue itself is resolved.
