### ISSUE TITLE
Conversations are re-downloaded on every login

### ISSUE THREAD

**Issue by blacklight** [hoehermann/purple-gowhatsapp#97]
Every time I log into my WhatsApp account through irssi+bitlbee all of my conversations are re-downloaded and the client receives tons of notifications.

This slows down irssi a lot, and it also pollutes the conversations bar with hundreds of entries.

The contacts associated to conversations aren't displayed in the bitlbee channel either.

It would be nice to have an option to avoid re-downloading all the conversations upon login, and ideally also display WhatsApp contacts in the nicks list.

**Comment by hoehermann** [comment]
### Receiving old messages
**Edit:** In bitlbee, the plug-in cannot keep track of which messages have already been processed as the account data-store is read-only.

You can set `max-history-seconds` to a value different from 0. All messages older than that will be discarded (old messages will get lost).

**Pre-edit answer (incorrect):** The plug-in keeps track of already received messages. However, it only remembers the IDs of the last 1000 messages. You can set `message-id-store-size` to a bigger value (e.g. 100000). This will have an impact on CPU whenever a message is received. Orthogonally, you can enable `message-timestamp-filter` by setting it to 1. This will assume that there are no messages lingering in the queue. Any message older than the most recently received message will be discarded.

### Contacts
Set `pull-contacts` to 1.

**Comment by blacklight** [comment]
@hoehermann thanks for the reply! The only thing that seemed to work on my irssi+bitlbee setup is setting `max-history-seconds` to something like one hour, neither setting `message-id-store-size` nor `message-timestamp-filter` prevent all the messages from being re-downloaded at login.

For the contacts part - I still can't see the WhatsApp contacts on the chat list, even if I have `pull-contacts = 'true'`. Chat rooms pop up when a message is received, but the nicks are not persisted on the list of accounts.

**Comment by yourealwaysbe** [comment]
Just a note on this -- the `message-id-store-size` and `message-timestamp-filter` don't work on BitlBee. This is because it needs to store data in the purple account, and BitlBee doesn't honor that (this is why we needed an extra password saving signal just for BitlBee).

The `max-history-seconds` option was a bodge i added to make BitlBee more usable.

**Comment by hoehermann** [comment]
@yourealwaysbe Oh, indeed. You already told me that on bitlbee those settings are read-only in regards to the session data. I failed to make the connection to this case. Anyway, the whatsmeow version keeps track of the messages in its internal database – so this issue will be closed as soon as the whatsmeow version is considered the new default. :)

**Comment by hoehermann** [comment]
I have now deprecated the old gowhatsapp branch. The whatsmeow re-write is the new default. I regard this issue as "fixed".
