### ISSUE TITLE
switching from gowhatsapp to whatsmeow

### ISSUE THREAD

**Issue by pkar70** [hoehermann/purple-gowhatsapp#98]
Please add to README or some other place in doc - does whatsmeow version takes account data and buddies list from gowhatsapp version, or user have to reconnect (scan QR code, etc.)?

**Comment by hoehermann** [comment]
A re-authentication is necessary. Session information from gowhatsapp cannot be used with the multi-device beta at all – even with official clients, you need to scan the code.
